#! /bin/csh -f

if (`uname` != "Darwin") then
  # Assuming to work on some HPC cluster
  # If HOST_NAME isn't defined yet, do it here...
  if (! $?HOST_NAME ) then
    if (-e whereami) then
      set HOST_NAME=`./whereami|tail -1`
    else
      set HOST_NAME="UNKNOWN"
    endif
    if ( $HOST_NAME == "*UNKNOWN*" ) then
      set HOST_NAME=default
    endif
    echo "Using HOST_NAME = $HOST_NAME"
  endif
else
  # Using MacOS, so assuming to work on a local device
  set HOST_NAME="DARWIN"
endif

# List of default compilers per HOST_NAME
switch ($HOST_NAME)
case "ASIPP":
case "CCFE":
case "CCFE-csd3":
case "FZJ":
case "GA":
case "IFERC":
case "IN-DA":
case "IPP-HGW":
case "IPR":
case "ITER":
case "JET":
case "KEIO":
case "KSTAR":
case "LEUVEN":
case "MPCDF":
case "NSCC":
case "SCNET":
case "SPBSTU":
case "SURFSARA":
case "SWIP":
  echo ifort64
  breaksw
case "CONTAINER":
case "DARWIN":
case "IPP":
case "IPPCR":
case "ITM":
case "JFRS":
case "LINUX":
case "MARCONI":
case "MEPHI":
case "NERSC":
case "ORNL":
case "PITAGORA":
case "PPPL":
case "WM":
  echo gfortran
  breaksw
case "ENEA":
  echo pgf90
  breaksw
default:
  echo ifort64
endsw
