#! /bin/tcsh -f

## -h                         print help
## -n                         dry run
## -s                         run B2.5 applications in stand-alone mode (no Eirene coupling)
## -m <mpi-launcher + args>   run mpi-version (example: b2run -m \"mpiexec -np 2\" b2mn)
## -d <debugger>              use debugger <debugger>

# if we are running at JET then do not rely on the automatic feature of searching in ../baserun, instead setup links
# XPB: not sure this is still needed
# if (${HOST_NAME} == "JET" && `basename $PWD` != "baserun") then
#   echo Special action is being taken since we are running at JET
#   foreach i (b2mn.dat b2fgmtry b2fpardf b2fstati b2frates)
#     if (! -s $i) then
#       echo Setting up a link to ../baserun/$i
#       ln -s ../baserun/$i
#     endif
#   end
# endif
# end

setenv SOLPSTOP "`determine_SOLPSTOP`"
if ($SOLPSTOP != "") then
  set RUNS=$SOLPSTOP/runs
else
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
  set RUNS=$PWD
endif
echo Using SOLPSTOP = $SOLPSTOP

loop:
  if(-s $RUNS/Makefile) goto endloop
  if ("$RUNS" == "/") then
    echo Makefile not found
    exit
  endif
  set RUNS=`dirname $RUNS`
  goto loop

endloop:
  set b2ex=""
  set debug=""
  if(! $?TIME) set TIME=time
  set RUN_OPTIONS=""
  if(! $?TAO) then
    set RUN_OPTIONS=""
  else
    set RUN_OPTIONS="-tao_monitor -tao_view_solution -tao_ls_view -tao_ls_type armijo ${TAO_OPT}"
  endif
  set KMP_AFFINITY=""
  set OMP_NUM_THREADS=1

argloop:
  if ("X${1}X" == "X-hX") then
    shift
    echo 'Usage: b2run [OPTIONS] [executable] < [Eirene input file] > [log file]'
    echo 'Launches a SOLPS run'
    echo ' '
    echo 'Optional arguments:'
    echo ' -b: for use with b2co to produce a provisional b2fstate file while the main code is running'
    echo ' -d <debugger>: launch run with debugger <debugger> (or with $DBX if <debugger> not specified)'
    echo ' -h: Prints this message'
    echo ' -m <mpi-launcher + args>: run mpi-version (example: b2run -m \"mpiexec -np 2\" b2mn)'
    echo ' -n: dry run. Will show the sequences of commands requested by b2run.'
    echo ' -o <options>: any additional run options'
    echo ' -s: request a B2.5 stand-alone run. No Eirene input file required then.'
    echo ' -t <number-of-threads> : request an OpenMP run with <number-of-threads> threads'
    echo ' -tgt: request a B2.5 run with tangent differentiated executable'
    echo ' -adj: request a B2.5 run with adjoint differentiated executable'
    echo ' -opt_tgt: request a B2.5 parameter optimization with tangent differentiated executable'
    echo ' -opt_adj: request a B2.5 parameter optimization with adjoint differentiated executable'
    echo ' '
    echo 'Executable: One of the following'
    echo ' b2ab: Build tables for advanced fluid neutral (AFN) boundary conditions'
    echo ' b2ag: Build the geometry files b2fgmtry and fort.30'
    echo ' b2ah: Build the run parameters file b2fpardf'
    echo ' b2ai: Build the initial state file b2fstati'
    echo ' b2ar: Build the atomic rates file b2frates'
    echo ' b2co: Recover from a plasmastate.xxxx file'
    echo ' b2fu: Convert from b2fplasmf to b2fplasma'
    echo ' b2md: Archive a run into MDSPLUS'
    echo ' b2mn: Main SOLPS-ITER run program'
    echo ' b2pl: Run the b2plot graphical post-processor'
    echo ' b2rd: Read an MDSPLUS archived run'
    echo ' b2ts: Generic post-processing program'
    echo ' b2uf: Convert from b2fplasma to b2fplasmf'
    echo ' b2xd: Convert to a SOLPS4.0 run'
    echo ' b2yg: Plot the geometry'
    echo ' b2yh: Plot the run parameters'
    echo ' b2yi: Plot the initial state'
    echo ' b2yi_gnuplot: Plot the initial state (using gnuplot)'
    echo ' b2ym: Produces movie output'
    echo ' b2yn: Plot the progress of inner iterations'
    echo ' b2yp: Plots the plasma state'
    echo ' b2yq: Plots the time evolution data'
    echo ' b2yr: Plot the atomic physics rates'
    echo ' b2yt: Convert a run to a different grid size or species list'
    echo ' b2mn_d: Main SOLPS-ITER run program differentiated in tangent mode'
    echo ' b2mn_b: Main SOLPS-ITER run program differentiated in adjoint mode'
    echo ' b2optim_tao: Parameter optimization with PETSc/TAO solver'
    echo ' '
    exit
  endif
  if ("X${1}X" == "X-nX") then
    shift
    set debug="-n"
    goto argloop
  endif
  if ("X${1}X" == "X-bX") then
    shift
    setenv B2FSTATE_ONLY yes
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    shift
    setenv STAND_ALONE yes
    goto argloop
  endif
  if ("X${1}X" == "X-diff_dX") then
    shift
    setenv STAND_ALONE yes
    setenv DIFF_D yes
    goto argloop
  endif
  if ("X${1}X" == "X-opt_dX") then
    shift
    setenv STAND_ALONE yes
    setenv OPT_D yes
    goto argloop
  endif
  if ("X${1}X" == "X-diff_bX") then
    shift
    setenv STAND_ALONE yes
    setenv DIFF_B yes
    goto argloop
  endif
  if ("X${1}X" == "X-opt_bX") then
    shift
    setenv STAND_ALONE yes
    setenv OPT_B yes
    goto argloop
  endif
  if ("X${1}X" == "X-tgtX") then
    shift
    setenv STAND_ALONE yes
    setenv TGT yes
    goto argloop
  endif
  if ("X${1}X" == "X-opt_tgtX") then
    shift
    setenv STAND_ALONE yes
    setenv OPT_TGT yes
    goto argloop
  endif
  if ("X${1}X" == "X-adjX") then
    shift
    setenv STAND_ALONE yes
    setenv ADJ yes
    goto argloop
  endif
  if ("X${1}X" == "X-opt_adjX") then
    shift
    setenv STAND_ALONE yes
    setenv OPT_ADJ yes
    goto argloop
  endif
  if ("X${1}X" == "X-diff_ddX") then
    shift
    setenv STAND_ALONE yes
    setenv DIFF_DD yes
    goto argloop
  endif
  if ("X${1}X" == "X-hess_tgtX") then
    shift
    setenv STAND_ALONE yes
    setenv HESS_TGT yes
    goto argloop
  endif
  if ("X${1}X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set first_mpi_arg="$1"
    set TMPI=`echo $argv | sed -e 's:^"::' -e 's:" .*::' -e 's:"$::' `
    set nargs=`echo "$first_mpi_arg" | awk '{print split($0,args," ")}'`
    if ($nargs > 1) then
      set nargs=1
    else
      set nargs=`echo $TMPI | awk '{print split($0,args," ")}'`
    endif
    if ($?SOLPS_MPIRUN) then
      if ("X${SOLPS_MPIRUN}X" != "XX") then
        set mpi_launcher=`echo "$TMPI" | awk '{print $1}'`
        set mpi_launcher_base=`basename "$mpi_launcher"`
        if ("X${mpi_launcher_base}X" == "XmpirunX" || \
            "X${mpi_launcher_base}X" == "XmpiexecX") then
          set mpi_args=`echo "$TMPI" | cut -d ' ' -f 2-`
          if ("X${mpi_args}X" == "X${TMPI}X") then
            set TMPI="$SOLPS_MPIRUN"
          else
            set TMPI="$SOLPS_MPIRUN $mpi_args"
          endif
        endif
      endif
    endif
    if ("X${TIME}X" == "XtimeX") then
      set TIME="$TMPI"
    else
      set TIME="$TIME $TMPI"
    endif
    mpiloop:
      if ($nargs > 0) then
        shift
        @ nargs = $nargs - 1
      else
        goto mpiloopend
      endif
      goto mpiloop
    mpiloopend:
    goto argloop
  endif
  if ("X${1}X" == "X-tX") then
    shift
    if (! $?SOLPS_OPENMP) then
      source $SOLPSTOP/SETUP/openmp
      set OPENMP_SET=yes
    endif
    set OMP_NUM_THREADS=$1
    shift
    goto argloop
  endif
  if ("X${1}X" == "X-dX") then
    shift
    if (! $?SOLPS_DEBUG) then
      source $SOLPSTOP/SETUP/debug
      set DEBUG_SET=yes
    endif
    if ("X${1}X" == "XX") then
      if ("X${TIME}X" == "XtimeX") then
        set TIME="$DBX"
      else
        set TIME="$DBX $TIME"
      endif
    else
      set next=$1
      set begin_next=`printf '%s' $next | cut -c1`
      set b2gin_next=`printf '%s' $next | cut -c-2`
      if ("X${begin_next}X" == "X-X") then
        set TIME="$DBX"
      else
        if ("X${b2gin_next}X" == "Xb2X") then
          set b2ex="${argv}"
          set TIME="$DBX"
          shift
        else
          set TIME="$1"
          shift
        endif
      endif
    endif
    goto argloop
  endif
  if ("X${1}X" == "X-oX") then
    shift
    set RUN_OPTIONS="$RUN_OPTIONS $1"
    shift
    goto argloop
  endif
  if ("X${b2ex}X" == "XX") then
    if ("X${argv}X" == "XX") then
      set b2ex="b2mn"
    else
      set b2ex="${argv}"
    endif
  endif
  echo "argument = "$b2ex
  set CMD=`echo $b2ex" " | sed -e 's: :.prt :g'`
  set B2EX=`echo $b2ex | cut -d ' ' -f 1`
  ${MAKE} $debug B2EX="$B2EX" TIME="$TIME" RUN_OPTIONS="$RUN_OPTIONS" OMP_NUM_THREADS=$OMP_NUM_THREADS -f $RUNS/Makefile $CMD
  unsetenv STAND_ALONE
  unsetenv B2FSTATE_ONLY
  if ($?MPI_SET)    source $SOLPSTOP/SETUP/nompi
  if ($?DEBUG_SET)  source $SOLPSTOP/SETUP/nodebug
  if ($?OPENMP_SET) source $SOLPSTOP/SETUP/noopenmp
