cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xxgs.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xxid.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xzmf.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xpne_st.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xvsg.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xvfx.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xvff.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xpnn.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xppb.F .
cp $SOLPSTOP/modules/B2.5/src/b2aux/b2xpnr.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/lower_case.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/isplusorminus.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/isadigit.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/isaletter.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/b2ptrdl.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/rlcomp.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/b2pwinm.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/b2pwinp.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/b2pwlprp.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/b2pwrdld.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/wallon.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/b2pwsort.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/rlshdw.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/ank_interface.F .
cp $SOLPSTOP/modules/B2.5/src/b2plot/species.F .
cp $SOLPSTOP/modules/B2.5/src/catalyst/fortranAdaptor.F90 .
cp $SOLPSTOP/modules/B2.5/src/convert/find_faces.F .
cp $SOLPSTOP/modules/B2.5/src/equations/b2nxcm.F .
cp $SOLPSTOP/modules/B2.5/src/equations/b2nxst.F .
cp $SOLPSTOP/modules/B2.5/src/ids/b2mod_constants.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/carre_constants.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/b2mod_cellhelper.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/tradui_constants.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/logging.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/helper.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/b2mod_grid_mapping.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/b2mod_connectivity.F90 .
cp $SOLPSTOP/modules/B2.5/src/ids/b2mod_interp.F90 .
cp $SOLPSTOP/modules/B2.5/src/input/b2rflb.F .
cp $SOLPSTOP/modules/B2.5/src/input/b2rusr.F .
cp $SOLPSTOP/modules/B2.5/src/input/b2ruzd.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_openmp.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_rates.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_geo_corner.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2cmfs.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_types.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_time.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_residuals.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_eirene_globals.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_mwti.F90 .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_cdf.F90 .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_ma28_for_us.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_eirbra.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2_to_astr* .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2cmgs.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2plot_wall_loading.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_ranges.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_work.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2plot_debug.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2us_debug.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_movies.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_geo2.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_solpstop.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_stack.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_eirsrt.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_chord_shift.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_version.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_tallies.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_neutr_src_scaling.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_wall.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_layer.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2plot.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_ysmp_sdrv.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_transport_models.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2mrel.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_braeir.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_anomalous_transport.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_ppout.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_sources.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_graphics.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_rdload.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2cmpa.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_b2cmpb.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_elements.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_pardiso.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_plasma.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2mod_convergence.F .
cp $SOLPSTOP/modules/B2.5/src/modules/b2us_work.F .
cp $SOLPSTOP/modules/B2.5/src/output/b2wdat.F .
cp $SOLPSTOP/modules/B2.5/src/output/b2wuzd.F .
cp $SOLPSTOP/modules/B2.5/src/output/tallies.F .
cp $SOLPSTOP/modules/B2.5/src/solvers/b2uxus.F .
cp $SOLPSTOP/modules/B2.5/src/solvers/b2uppo.F .
cp $SOLPSTOP/modules/B2.5/src/sources/average.F .
cp $SOLPSTOP/modules/B2.5/src/sources/setwrk0.F .
cp $SOLPSTOP/modules/B2.5/src/sources/integrate.F .
cp $SOLPSTOP/modules/B2.5/src/sources/ggfill.F .
cp $SOLPSTOP/modules/B2.5/src/transport/b2trcn.F .
cp $SOLPSTOP/modules/B2.5/src/transport/b2trca.F .
cp $SOLPSTOP/modules/B2.5/src/transport/b2trcv.F .
cp $SOLPSTOP/modules/B2.5/src/transport/b2trhw.F .
cp $SOLPSTOP/modules/B2.5/src/transport/b2trtf.F .
cp $SOLPSTOP/modules/B2.5/src/transport/b2trnu.F .
cp $SOLPSTOP/modules/B2.5/src/user/batch_average.F .
cp $SOLPSTOP/modules/B2.5/src/user/b2mod_file.F .
cp $SOLPSTOP/modules/B2.5/src/user/b2mod_trace.F .
cp $SOLPSTOP/modules/B2.5/src/user/b2mod_bln* .
cp $SOLPSTOP/modules/B2.5/src/user/b2mod_wr* .
cp $SOLPSTOP/modules/B2.5/src/user/b2mod_usrtrc.F .
cp $SOLPSTOP/modules/B2.5/src/user/combfile.F .
cp $SOLPSTOP/modules/B2.5/src/user/parsehdr.F .
cp $SOLPSTOP/modules/B2.5/src/user/cdfmovie.F .
cp $SOLPSTOP/modules/B2.5/src/user/map_and_interpolate_cf.F .
cp $SOLPSTOP/modules/B2.5/src/utility/b2mod_ipmain.F .
cp $SOLPSTOP/modules/B2.5/src/utility/xer* .
cp $SOLPSTOP/modules/B2.5/src/utility/b2mod_xerset.F .
cp $SOLPSTOP/modules/B2.5/src/utility/b2mod_subsys.F .
cp $SOLPSTOP/modules/B2.5/src/utility/b2mod_lw* .
cp $SOLPSTOP/modules/B2.5/src/utility/smin.F .
cp $SOLPSTOP/modules/B2.5/src/utility/smax.F .
cp $SOLPSTOP/modules/B2.5/src/utility/damax.F .
cp $SOLPSTOP/modules/B2.5/src/utility/open_file.F .
cp $SOLPSTOP/modules/B2.5/src/utility/ipget* .
cp $SOLPSTOP/modules/B2.5/src/utility/mstep.F .
cp $SOLPSTOP/modules/B2.5/src/utility/hybr.F .
cp $SOLPSTOP/modules/B2.5/src/utility/upwind.F .
cp $SOLPSTOP/modules/B2.5/src/utility/intface.F .
cp $SOLPSTOP/modules/B2.5/src/utility/ilutern_us_solps.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cfru* .
cp $SOLPSTOP/modules/B2.5/src/utility/cfwuch.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cfwuin.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cfwure.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cfopen.F .
cp $SOLPSTOP/modules/B2.5/src/utility/get_jsep.F .
cp $SOLPSTOP/modules/B2.5/src/utility/prg* .
cp $SOLPSTOP/modules/B2.5/src/utility/streql.F .
cp $SOLPSTOP/modules/B2.5/src/utility/machsfr.F .
cp $SOLPSTOP/modules/B2.5/src/utility/ma28copy.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cdf_routines.F .
cp $SOLPSTOP/modules/B2.5/src/utility/interp1d.F .
cp $SOLPSTOP/modules/B2.5/src/utility/intp_* .
cp $SOLPSTOP/modules/B2.5/src/utility/harm.F .
cp $SOLPSTOP/modules/B2.5/src/utility/nancheck.F .
cp $SOLPSTOP/modules/B2.5/src/utility/strip_spaces.F .
cp $SOLPSTOP/modules/B2.5/src/utility/is_comment.F .
cp $SOLPSTOP/modules/B2.5/src/utility/uxcm.F .
cp $SOLPSTOP/modules/B2.5/src/utility/ratio.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cpeir_* .
cp $SOLPSTOP/modules/B2.5/src/utility/epoch_seconds.F .
cp $SOLPSTOP/modules/B2.5/src/utility/bfill.F .
cp $SOLPSTOP/modules/B2.5/src/utility/len_of_digits.F .
cp $SOLPSTOP/modules/B2.5/src/utility/prvrt* .
cp $SOLPSTOP/modules/B2.5/src/utility/chcase.F .
cp $SOLPSTOP/modules/B2.5/src/utility/trilinear_int.F .
cp $SOLPSTOP/modules/B2.5/src/utility/lefta.F .
cp $SOLPSTOP/modules/B2.5/src/utility/sys* .
cp $SOLPSTOP/modules/B2.5/src/utility/intersects.F .
cp $SOLPSTOP/modules/B2.5/src/utility/jobnam.F .
cp $SOLPSTOP/modules/B2.5/src/utility/nagsubst.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cfvers.F .
cp $SOLPSTOP/modules/B2.5/src/utility/daytim.F .
cp $SOLPSTOP/modules/B2.5/src/utility/usrnam.F .
cp $SOLPSTOP/modules/B2.5/src/utility/strcopy.F .
cp $SOLPSTOP/modules/B2.5/src/utility/dfmin.F .
cp $SOLPSTOP/modules/B2.5/src/utility/dseval.F .
cp $SOLPSTOP/modules/B2.5/src/utility/dspline.F .
cp $SOLPSTOP/modules/B2.5/src/utility/cond_coef.F .
cp $SOLPSTOP/modules/B2.5/src/utility/my_outi_us.F .
cp $SOLPSTOP/modules/B2.5/src/utility/solve_covariance.F .
cp $SOLPSTOP/modules/B2.5/src/utility/calc_err.F .
cp $SOLPSTOP/modules/B2.5/src/utility/interp2d.F .
cp $SOLPSTOP/modules/B2.5/src/utility/invert_matrix.F .
cp $SOLPSTOP/modules/B2.5/src/utility/mass_density.F .
cp $SOLPSTOP/modules/B2.5/src/utility/ma28copy.F .
cp $SOLPSTOP/modules/B2.5/src/utility/find_loc.F .
cp $SOLPSTOP/modules/B2.5/src/utility/my_out.F .
