#! /bin/tcsh -f
cd baserun
foreach i (b2ag.dat b2ah.dat b2ai.dat b2ar.dat)
  [ -s $i ] && touch $i
end
sleep 1
touch b2ag.prt
[ -s b2fgmtry ] && touch b2fgmtry || echo 'No valid b2fgmtry file found'
sleep 1
touch b2ah.prt
[ -s b2fpardf ] && touch b2fpardf || echo 'No valid b2fpardf file found'
sleep 1
touch b2ai.prt
[ -s b2fstati ] && touch b2fstati || echo 'No valid b2fstati file found'
sleep 1
ln -sf $SOLPSTOP/modules/B2.5/Database/stra.dat .
ln -sf $SOLPSTOP/modules/B2.5/Database/weis.dat .
ln -sf $SOLPSTOP/modules/Eirene/Database/AMJUEL .
ln -sf $SOLPSTOP/modules/Eirene/Database/HYDHEL .
touch b2ar.prt
[ -s b2frates ] && touch b2frates || echo 'No valid b2frates file found'
