#! /bin/tcsh -f

set NAME=/tmp/.run.$$.$USER.`date +%Y%m%d%H%M%S`
set EMAIL=`get_git_email`
set JOB_NAME="SOLPS-ITER"
set NODES=1
set PROCS=1
set THREADS=1
set hours=48
set mem=8GB
echo Your email is $EMAIL

set compress_arg=""
set compress_suffix=""
set MPIOPTS=""
set standalone_arg=""
set coupled_suffix="_coupled"
set LOOP_OPTS=""
set OPTOPTS=""
setenv SOLPS_OPT ""

setenv SOLPSTOP "`determine_SOLPSTOP`"
if ($SOLPSTOP == "") then
  setenv SOLPSTOP "`echo $PWD | sed 's:/runs/.*::'`"
endif

argloop:
  if ("X${1}X" == "X-hX") then
    cat <<EOF

Help for $0

This script is used to submit SOLPS-ITER jobs to the PBS batch system on the CCFE Cumulus cluster.

Usage:

  `basename $0` {options} {<<SCRIPT>>}

where the optional <<SCRIPT>> is the SLURM submission file to be used

Available options are:
  -j <<JOB NAME>>          set the job name (default $JOB_NAME)
  -z                       compress run.log using gzip
  -s                       specify a standalone B2.5 run
  -tgt                     specify a standalone B2.5 run with tangent AD derivatives
  -adj                     specify a standalone B2.5 run with adjoint AD derivatives
  -hess_tgt                specify a standalone B2.5 run with tangent-over-tangent hessian AD derivatives
  -opt_tgt <<OPT_OPTIONS>> specify a standalone B2.5 optimization run with tangent AD derivatives
  -opt_adj <<OPT_OPTIONS>> specify a standalone B2.5 optimization run with adjoint AD derivatives
  -m <<MPI OPTIONS>>       use the MPI options specified (default serial version)
  -t <<THREADS>>           use OpenMP parallelization with <<THREADS>> threads (default $THREADS)
  -T <<HOURS>>             number of elapsed hours requested (default $hours)
  -M <<MEM_SIZE>>          memory size (default $mem)

EOF
    exit
  endif
  if ("X${1}X" == "X-jX") then
    shift
    set JOB_NAME="$1"
    echo Job name is ${JOB_NAME}
    shift
    set HELP_STRING=\"${JOB_NAME}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-j ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-zX") then
    set compress_arg="| gzip -9"
    set compress_suffix=".gz"
    echo run.log will be compressed
    shift
    set LOOP_OPTS="-z ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-sX") then
    set standalone_arg="-s"
    set coupled_suffix=""
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5"
    echo Asking for a B2.5 standalone run
    shift
    set LOOP_OPTS="-s ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-opt_tgtX") then
    shift
    set standalone_arg="-s"
    setenv SOLPS_OPT "opt_"
    if (! $?SOLPS_TGT) then
      source $SOLPSTOP/SETUP/tgt
    endif
    set OPTOPTS="$1"
    if (! $?OPT) then
      echo No optimization library specified, reverting to PETSc/TAO
      source $SOLPSTOP/SETUP/tao "${OPTOPTS}"
    endif
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5_OPT_TGT"
    echo Asking for a B2.5 standalone optimization with tangent AD
    shift
    set HELP_STRING="${OPTOPTS}"
    set LOOP_OPTS="-opt_tgt '${OPTOPTS}' ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-opt_adjX") then
    shift
    set standalone_arg="-s"
    setenv SOLPS_OPT "opt_"
    if (! $?SOLPS_TGT) then
      source $SOLPSTOP/SETUP/adj
    endif
    set OPTOPTS="$1"
    if (! $?OPT) then
      echo No optimization library specified, reverting to PETSc/TAO
      source $SOLPSTOP/SETUP/tao "${OPTOPTS}"
    endif
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5_OPT_ADJ"
    echo Asking for a B2.5 standalone optimization with adjoint AD
    shift
    set HELP_STRING="${OPTOPTS}"
    set LOOP_OPTS="-opt_adj '${OPTOPTS}' ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-tgtX") then
    set standalone_arg="-s"
    if (! $?SOLPS_TGT) then
      source $SOLPSTOP/SETUP/tgt
    endif
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5_TGT"
    echo Asking for a B2.5 standalone run with tangent AD
    shift
    set LOOP_OPTS="-tgt ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-adjX") then
    set standalone_arg="-s"
    if (! $?SOLPS_ADJ) then
      source $SOLPSTOP/SETUP/adj
    endif
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5_ADJ"
    echo Asking for a B2.5 standalone run with adjoint AD
    shift
    set LOOP_OPTS="-adj ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-hess_tgtX") then
    set standalone_arg="-s"
    if (! $?SOLPS_HESS_TGT) then
      source $SOLPSTOP/SETUP/hess_tgt
    endif
    if ($JOB_NAME == "SOLPS-ITER") set JOB_NAME="B2.5_HESS_TGT"
    echo Asking for a B2.5 standalone run with tangent hessian AD
    shift
    set LOOP_OPTS="-hess_tgt ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-mX") then
    shift
    if (! $?SOLPS_MPI) then
      source $SOLPSTOP/SETUP/mpi
      set MPI_SET=yes
    endif
    set I_MPI_SHM_LMT=shm
    set MPIOPTS="$1"
    echo Using MPI options: $MPIOPTS
    set PROCS=`echo $MPIOPTS | awk.transpose | grep -A 1 "\-np" | tail -n 1`
    echo Asking for MPI run with a total of $PROCS processors
    shift
    set HELP_STRING=`echo \"$MPIOPTS\"`
#    echo $HELP_STRING
    set LOOP_OPTS="-m ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-tX") then
    shift
    if (! $?SOLPS_OPENMP) then
      source $SOLPSTOP/SETUP/openmp
      set OPENMP_SET=yes
    endif
    set THREADS="$1"
    echo Asking for OpenMP run with $THREADS threads
    shift
    set HELP_STRING=\"${THREADS}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-t ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-TX") then
    shift
    set hours="$1"
    if ( $hours == 1) then
      echo Requested time is ${hours} hour
    else
      echo Requested time is ${hours} hours
    endif
    shift
    set HELP_STRING=\"${hours}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-T ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif
  if ("X${1}X" == "X-MX") then
    shift
    set mem="$1"
    echo Requested memory is ${mem}
    shift
    set HELP_STRING=\"${mem}\"
#    echo $HELP_STRING
    set LOOP_OPTS="-M ${HELP_STRING} ${LOOP_OPTS}"
    goto argloop
  endif

if ($1 == "") then
  echo No argument is specified. Looking for QSUB.cumulus
  set QSUB=`climb_and_look_for QSUB.cumulus`
  if ($QSUB == "//QSUB.cumulus") then
    if (-s $SOLPSTOP/runs/QSUB.cumulus) then
      set QSUB="$SOLPSTOP/runs/QSUB.cumulus"
    else
      set QSUB=""
    endif
  endif
else if (-s $1) then
  echo Submission file $1 is specified as an argument.
  echo Submission file $1 is found in current directory
  set QSUB=$1
else
  echo Submission file $1 is specified as an argument.
  echo Looking for submission file $1
  set QSUB=`climb_and_look_for $1`
  if ($QSUB == "//"$1) then
    if (-s $SOLPSTOP/runs/$1) then
      set QSUB="$SOLPSTOP/runs/$1"
      echo Submission file $QSUB is found
    else
      set QSUB=""
    endif
  else
    echo Submission file $QSUB is found
  endif
endif
if($QSUB == "") then
  echo No CUMULUS submission file $1 found. Exiting.
  exit 1
endif

echo Using submission file template $QSUB
echo For loop resubmission following options will be used: $LOOP_OPTS

sed \
  -e 's:#PWD#:'$PWD':g' \
  -e 's:#SOLPSTOP#:'$SOLPSTOP':g' \
  -e 's:#EMAIL#:'$EMAIL':g' \
  -e "s:#MPIOPTS#:'$MPIOPTS':g" \
  -e 's:#NODES#:'$NODES':g' \
  -e 's:#PROCS#:'$PROCS':g' \
  -e 's:#THREADS#:'$THREADS':g' \
  -e 's:#MEM#:'$mem':g' \
  -e 's:#HOURS#:'$hours':g' \
  -e 's:#JOBNAME#:'$JOB_NAME':g' \
  -e 's:#USER#:'$USER':g' \
  -e 's:#LOOPOPTS#:'"$LOOP_OPTS"':g' \
  -e 's:#COMPRESS_ARG#:'"$compress_arg"':g' \
  -e 's:#COMPRESS_SUFFIX#:'"$compress_suffix"':g' \
  -e 's:#STANDALONE_ARG#:'"$standalone_arg"':g' \
  -e 's:#COUPLED_SUFFIX#:'"$coupled_suffix"':g' \
  < $QSUB > $NAME

update_solps_run_status -n "Submitted at `date`"

qsub -V -S /bin/tcsh $NAME
