#! /usr/bin/env ksh

[ "$DEVICE" = '' ] && {
  print -u2 -n -- "No DEVICE selected. Please provide a device name\n "
  read u
  export DEVICE=$u
} || {
  echo "DEVICE = " $DEVICE
}
[ "$DEVICE" = 'iter' ] && {
  imasdb ITER > /dev/null
} || {
  imasdb $DEVICE > /dev/null
}
[ "$AL_VERSION" = '' ] && {
  export AL_MAJOR_VERSION=`echo $UAL_VERSION | cut -d '.' -f 1`
} || {
  export AL_MAJOR_VERSION=`echo $AL_VERSION | cut -d '.' -f 1`
}
export IMAS_MAJOR_VERSION=`echo $IMAS_VERSION | cut -d '.' -f 1`
[ "$IMASDIR" = '' ] && {
  [ $AL_MAJOR_VERSION = 5 ] && {
    export IMASDIR=/work/projects/solps-iter/${USER}/imasdb/${DATABASE}/${IMAS_MAJOR_VERSION}
  } || {
    export IMASDIR=/work/projects/solps-iter/${USER}/imasdb/${DATABASE}/${IMAS_MAJOR_VERSION}/0
  }
} || {
  echo "IMASDIR = " $IMASDIR
}
[ $AL_MAJOR_VERSION = 5 ] && {
  echo "Updating .yaml file for IDS pulse number "$1
} || {
  echo "Updating .yaml file for IDS shot number "$1
}
echo "New run number "$3" supersedes old run number "$2
shotnumber=`echo $1`
typeset -i shot
shot=`echo $1`
[ "$DEVICE" = 'iter' ] && {
  shot=$shot-100000
}
[ $shot -ge 30000 ] && {
  shot=$shot-30000
} || {
  [ $shot -ge 20000 ] && {
    shot=$shot-20000
  } || {
    [ $shot -ge 10000 ] && {
      shot=$shot-10000
    }
  }
}
typeset -i oldrun
typeset -i newrun
oldrun=`echo $2`
newrun=`echo $3`
al5yaml=ids_001.yaml
al5watcher=ids_001.watcher
[ $oldrun -ge 1000 ] && {
  al4yaml=ids_${shotnumber}$2.yaml
  al4watcher=ids_${shotnumber}$2.watcher
} || {
  [ $oldrun -ge 100 ] && {
    al4yaml=ids_${shotnumber}0$2.yaml
    al4watcher=ids_${shotnumber}0$2.watcher
  } || {
    [ $oldrun -ge 10 ] && {
      al4yaml=ids_${shotnumber}00$2.yaml
      al4watcher=oldyaml=ids_${shotnumber}00$2.watcher
    } || {
      al4yaml=ids_${shotnumber}000$2.yaml
      al4watcher=ids_${shotnumber}000$2.watcher
    }
  }
}
export AL5DIR=${IMASDIR}/${shotnumber}/${oldrun}
[ $AL_MAJOR_VERSION = 5 ] && {
  export AL4DIR=${IMASDIR}/0
  export NEWDIR=${IMASDIR}/${shotnumber}/${newrun}
  newyaml=ids_001.yaml
  newwatcher=ids_001.watcher
} || {
  export AL4DIR=${IMASDIR}
  export NEWDIR=${IMASDIR}
  [ $newrun -ge 1000 ] && {
    newyaml=ids_${shotnumber}$3.yaml
    watcher=ids_${shotnumber}$3.watcher
  } || {
    [ $newrun -ge 100 ] && {
      newyaml=ids_${shotnumber}0$3.yaml
      watcher=ids_${shotnumber}0$3.watcher
    } || {
      [ $newrun -ge 10 ] && {
        newyaml=ids_${shotnumber}00$3.yaml
        watcher=ids_${shotnumber}00$3.watcher
      } || {
        newyaml=ids_${shotnumber}000$3.yaml
        watcher=ids_${shotnumber}000$3.watcher
      }
    }
  }
}
echo "Old YAML directories :"${AL4DIR} ${AL5DIR}
[ $3 != $2 ] && {
  echo "Looking for "${AL5DIR}/${al5yaml}
  [ -r ${AL5DIR}/${al5yaml} ] && {
    cp ${AL5DIR}/${al5yaml} .
    oldyaml=${al5yaml}
  } || {
    echo "Looking for "${AL4DIR}/${al4yaml}
    [ -r ${AL4DIR}/${al4yaml} ] && {
      cp ${AL4DIR}/${al4yaml} .
      oldyaml=${al4yaml}
    } || {
      echo "Looking for "/work/imas/shared/imasdb/ITER/3/${shotnumber}/${oldrun}/${al5yaml}
      [ -r /work/imas/shared/imasdb/ITER/3/${shotnumber}/${oldrun}/${al5yaml} ] && {
        cp /work/imas/shared/imasdb/ITER/3/${shotnumber}/${oldrun}/${al5yaml} .
        oldyaml=${al5yaml}
      } || {
        echo "Looking for "/work/imas/shared/imasdb/ITER/3/0/${al4yaml}
        [ -r /work/imas/shared/imasdb/ITER/3/0/${al4yaml} ] && {
          cp /work/imas/shared/imasdb/ITER/3/0/${al4yaml} .
          oldyaml=${al4yaml}
        } || {
          echo "Old case YAML file not found. Exit"
          exit 1
        }
      }
    }
  }
  [ -r ${AL5DIR}/${al5watcher} ] && {
    cp ${AL5DIR}/${al5watcher} .
    oldwatcher=${al5watcher}
  } || {
    [ -r ${AL4DIR}/${al4watcher} ] && {
      cp ${AL4DIR}/${al4watcher} .
    oldwatcher=${al4watcher}
    } || {
      [ -r /work/imas/shared/imasdb/ITER/3/${shotnumber}/${oldrun}/${al5watcher} && {
        cp /work/imas/shared/imasdb/ITER/3/${shotnumber}/${oldrun}/${al5watcher} .
        oldwatcher=${al5watcher}
      } || {
        [ -r /work/imas/shared/imasdb/ITER/3/0/${al4watcher} ] && {
        cp /work/imas/shared/imasdb/ITER/3/0/${al4watcher} .
        oldwatcher=${al4watcher}
        } || {
          echo "Old case watcher file not found. Exit"
          exit 2
        }
      }
    }
  }
  typeset -i yaml_lines
  typeset -i tail_lines
  typeset -i status_line
  typeset -i replace_line
  typeset -i reference_line
  typeset -i responsible_line
  reference=`grep -A1 "reference_name:" ${oldyaml} | tail -n 1 | cut -d ':' -f 2`
  yaml_lines=`cat ${oldyaml} | wc -l`
  status_line=`grep -n "status:" ${oldyaml} | cut -d ':' -f 1`
  head -n ${status_line} $oldyaml > $oldyaml.2
  echo "    obsolete" >> $oldyaml.2
  tail_lines=yaml_lines-(status_line+1)
  tail -n $tail_lines $oldyaml >> $oldyaml.2
  replace_line=`grep -n "replaces:" ${oldyaml}.2 | cut -d ':' -f 1`
  head -n ${replace_line} ${oldyaml}.2 > $oldyaml.3
  echo "    replaced_by: ("$shotnumber","$3")" >> $oldyaml.3
  tail_lines=yaml_lines-(replace_line+1)
  tail -n $tail_lines $oldyaml.2 >> $oldyaml.3
  yaml_lines=`cat ${newyaml} | wc -l`
  status_line=`grep -n "status:" ${newyaml} | cut -d ':' -f 1`
  head -n ${status_line} $newyaml > $newyaml.2
  echo "    active" >> $newyaml.2
  tail_lines=yaml_lines-(status_line+1)
  tail -n $tail_lines $newyaml >> $newyaml.2
  reference_line=`grep -n "reference_name:" ${newyaml}.2 | cut -d ':' -f 1`
  head -n ${reference_line} $newyaml.2 > $newyaml.3
  echo "   "$reference >> $newyaml.3
  tail_lines=yaml_lines-(reference_line+1)
  tail -n $tail_lines $newyaml.2 >> $newyaml.3
  responsible_line=`grep -n "responsible_name:" ${newyaml}.3 | cut -d ':' -f 1`
  head -n ${responsible_line} $newyaml.3 > $newyaml.4
  echo "    "`get_git_name` >> $newyaml.4
  tail_lines=yaml_lines-(responsible_line+1)
  tail -n $tail_lines $newyaml.3 >> $newyaml.4
  replace_line=`grep -n "database_relations:" ${newyaml}.4 | cut -d ':' -f 1`
  head -n ${replace_line} $newyaml.4 > $newyaml.5
  echo "    replaces: ("$shotnumber","$2")" >> $newyaml.5
  tail_lines=yaml_lines-(replace_line+1)
  tail -n $tail_lines $newyaml.4 >> $newyaml.5
  [ $shot -ge 3000 ] && {
    sed -e 's|workflow: tbd|workflow: SOLPS-ITER|' -e 's|type: tbd|type: predictive|' < $newyaml.5 > $newyaml.6
  } || {
    sed -e 's|workflow: tbd|workflow: SOLPS|' -e 's|type: tbd|type: predictive|' < $newyaml.5 > $newyaml.6
  }
  mv $oldyaml.3 ${OLDDIR}/$oldyaml
  mv $newyaml.6 ${NEWDIR}/$newyaml
  [ $PWD != $NEWDIR ] && {
    [ -r $watcher ] && {
      mv $watcher ${NEWDIR}/
    } || {
      cp $oldwatcher ${NEWDIR}/$watcher
    }
    rm $oldyaml $newyaml
  }
  rm $oldyaml.2
  rm $newyaml.2 $newyaml.3 $newyaml.4 $newyaml.5
  echo "IDS run number for case ${shotnumber} updated to $3 from $2 !"
}

