#! /usr/bin/env tcsh

# Set the Miniforge installation path
set CONDA_ROOT = "$SOLPSTOP/lib/${HOST_NAME}.${COMPILER}/miniforge3"

if (! -d "${CONDA_ROOT}" ) then

  echo
  echo "The miniforge package manager will be located in "
  echo "${CONDA_ROOT}"
  echo -n "Do you wish to continue? (y/n) [y] "
  set CONDA_INSTALL = $<

  if ( "$CONDA_INSTALL" == "" ) then
    set CONDA_INSTALL = "y"
  endif

  if ( "$CONDA_INSTALL" == "y" ) then

    # Make sure the parent directory exists
    if (! -d "${SOLPSTOP}/lib/${HOST_NAME}.${COMPILER}" ) then
      mkdir -p "${SOLPSTOP}/lib/${HOST_NAME}.${COMPILER}"
    endif

    # Go to the installation directory
    cd $SOLPSTOP/lib/${HOST_NAME}.${COMPILER}

    # Detect OS and architecture
    set OS = `uname -s`
    set ARCH = `uname -m`
    if ( "$OS" == "Linux" && "$ARCH" == "x86_64" ) then
      set MINIFORGE_INSTALLER = "Miniforge3-Linux-x86_64.sh"
    else if ( "$OS" == "Linux" && "$ARCH" == "aarch64" ) then
      set MINIFORGE_INSTALLER = "Miniforge3-Linux-aarch64.sh"
    else
      echo "Unsupported OS/architecture: $OS $ARCH"
      exit 1
    endif
    
    # Download Miniforge installer
    wget https://github.com/conda-forge/miniforge/releases/latest/download/${MINIFORGE_INSTALLER}
    
    # Install Miniforge in batch mode at $CONDA_ROOT
    bash ${MINIFORGE_INSTALLER} -b -p $CONDA_ROOT
    
    # Remove installer
    rm ${MINIFORGE_INSTALLER}

    # Initialize conda
    ${CONDA_ROOT}/bin/conda init tcsh

    echo
    echo miniforge package manager successfully installed.

  else
    echo miniforge package manager still not installed.
  endif

else

  echo miniforge package manager already locally installed.

endif
