#! /bin/tcsh -f
## strip git hashes and cost function information from run.log
if ( -s run.log ) then
  grep -i -w 'version' run.log >! run.info
  grep -e 'ntim' run.log | tail >> run.info
  grep -i 'stopping' run.log | tail >> run.info
  grep -i -w 'Calculating gradient of' run.log >> run.info
  set npar_opt=`grep -i npar_opt run.log | awk '{print $3}' | awk -F"," '{print $1}'`
  echo npar_opt = $npar_opt >> run.info
  @ npar_opt = $npar_opt + 1
  grep -i -A$npar_opt 'vec object' run.log >> run.info
  grep -i 'Number of cost functions' run.log | tail -n 1 >> run.info
  set NNN=`grep -i 'Number of cost functions' run.info | gawk '{print $5}'`
  if ( `grep -c gradient run.log` > 0) then
   @ NNN = $NNN * 2
  endif
   @ NNN = $NNN * 10
  grep -i -w 'cost function' run.log | tail -n $NNN >> run.info
  grep -i -w 'cost function value' run.log | tail -n $NNN >> run.info
  grep -i 'gradient' -A1 run.log | grep -i -v tao | tail -n 200 >> run.info
  grep -i 'hessian' run.log | grep -i -v tao | tail -n 400 >> run.info
else
  echo "No run.log file present"
endif
