#!/bin/bash

ext=save
#In case of save some files (trc, trg and last10) have to be added in the process of backup
SAVE_FILES_BASE="b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace b2fgmtry b2fpardf b2frates b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters b2.feedback_save.parameters b2.wall_save.parameters input.dat eirene.input.json eirene_add_surfaces.input.json eirene_physics_model.input.json eirene_AMData.json user_data.input eirene_input_json.out fort.1 fort.10 fort.11 fort.13 fort.14 fort.15 fort.21 fort.22 fort.31 fort.33 fort.34 fort.35 fort.44 fort.44_aver fort.46 fort.46_aver .VarID trg_sum.dat b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc last_2d_out last_2d_out_f box.b2p run.log.gz dsa dsi dsl dsL dsLP dsr dsR dsRP dstl dsTL dsTLP dstr dsTR dsTRP"
SAVE_DIR="tracing batch_av output b2pl_PS"

backup=backup
label=`date +"%Y%m%d"`
BK_LAST10=`ls *.last10 2>/dev/null`
BK_TRC=`ls -lt trc.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
BK_TRG=`ls -lt trg.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
BK_FILES="b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace b2frates b2fpardf b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters b2.feedback_save.parameters b2.wall_save.parameters input.dat eirene.input.json eirene_add_surfaces.input.json eirene_physics_model.input.json eirene_AMData.json user_data.input eirene_input_json.out fort.1 fort.10 fort.11 fort.13 fort.14 fort.15 fort.31 fort.44 fort.44_aver fort.46 fort.46_aver"
BK_MV_FILES="b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc"
BK_MV_DIR="tracing batch_av"

user=`whoami`
CURRENT_DIR=${PWD/}
SCR_DIR=/home/ITER/$user/scratch
SCR_MARK=.scrdir
SRC_MARK=.srcdir
WRK_PREF=wrk
BR=baserun
if [ -f "$SCR_MARK" ]
then
  DW_DIR=`cat $SCR_MARK`
else
  stamp=`date +%s`
  DW_DIR=$SCR_DIR/$WRK_PREF.$stamp
fi
BRUN=`echo $CURRENT_DIR | rev | cut -f 2- -d "/" | rev`
BRUN=$BRUN/$BR
RRUN=run
RUNCHK=b2mn.dat
UP_DIR=$CURRENT_DIR
BSR_LINKS="b2fgmtry b2ag.dat b2fpardf b2ah.dat b2frates b2ar.dat fort.30 fort.33 fort.34 fort.35 b2fstati b2ai.dat input.eir input.dat param.dg"
SCR_FILES="b2fstati fort.10 fort.11 fort.13 fort.14 fort.15 fort.44 fort.44_aver fort.46 fort.46_aver .VarID b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc box.b2p SOLPSTOP"
SCR_LINKS="b2mn.dat b2.boundary.parameters b2.transport.parameters b2.user.parameters b2.feedback_control.parameters b2.neutrals.parameters b2.numerics.parameters b2.transport.inputfile b2.sources.profile b2.atomic_physics_rescale.parameters b2.feedback_save.parameters b2.wall_save.parameters b2fgmtry b2fpardf b2frates input.dat eirene.input.json eirene_add_surfaces.input.json eirene_physics_model.input.json eirene_AMData.json user_data.input eirene_input_json.out fort.21 fort.22 fort.31 fort.33 fort.34 fort.35"
SCR_TOP="SOLPSTOP"
SCR_DIR="tracing batch_av"
SRC_FILES="b2fstati b2fstate b2fplasma b2fparam b2fmovie b2ftrack b2ftrace fort.10 fort.11 fort.13 fort.14 fort.15 fort.31 fort.44 fort.44_aver fort.46 fort.46_aver b2.feedback_save.parameters.i fort.11.i fort.13.i fort.14.i fort.15.i fort.44.i fort.46.i b2time.nc b2tallies.nc b2batch.nc b2wall.nc balance.nc run.log.gz"
SRC_DIR="tracing batch_av output"

NAME=${0##*/}
[ ! $# -eq 0 ] && arg=$1
case $arg in
  -l)
    echo "saveb2 -l: local backup"
    mode=l
    ;;
  -s)
    echo "saveb2 -s: storing finished run(s)"
    mode=s
    ;;
  -c)
    echo "saveb2 -c: copying data to scratch"
    mode=c
    ;;
  -g)
    echo "saveb2 -g: get data from scratch"
    mode=g
    ;;
  -r)
    echo "saveb2 -r: cleaning scratch data"
    mode=r
    ;;
   *)
    echo "$NAME - used to create local and final backups. "
    echo "USAGE: "
    echo "	saveb2 -l             : backup local files between b2run sessions"
    echo "	saveb2 -s dir_name(s) : store finished runs to dirname(s).$ext"
    echo "	saveb2 -c             : copy run data to scratch and setup workspace there"
    echo "	saveb2 -g             : copy run data from scratch"
    echo "	saveb2 -r             : clean run data from scratch"
    exit 1
esac

shift

{
[ $mode == "l" ] && {

  echo "backup local files to $backup.$label"
  if [ ! -d $backup.$label ]
  then
    mkdir $backup.$label
    for f in $BK_FILES; do {
      [ -f "$f" ] && echo "cp $f $backup.$label/$f" && cp "$f" "$backup.$label/$f"
      if [ ! -s "$backup.$label/$f" ]
      then
        echo "warning: $f either absent or empty"
      fi
    }; done
    for ff in $BK_MV_FILES; do {
      [ -f "$ff" ] && echo "mv $ff $backup.$label/$ff" && mv "$ff" "$backup.$label/$ff"
      if [ ! -s "$backup.$label/$ff" ]
      then
        echo "warning: $ff either absent or empty"
      fi
    }; done
    for fd in $BK_MV_DIR; do {
      [ -d "$fd" ] && [ ! -z "$(ls -A "$fd")" ] && echo "mv $fd $backup.$label/$fd" && mv "$fd" "$backup.$label/$fd"
      if [ ! -d "$backup.$label/$df" ]
      then
        echo "warning: $fd either absent or empty"
      fi
    }; done
  else
    echo "$backup.$label already present, aborting..."
  fi
  }

} || {

[ $mode == "s" ] && {

  [ $# -eq 0 ] && {
    echo "ERROR: No argument provided, nothing to save"
    } || {
    for run in "$@"; do {
      hlp=`echo $run | rev`
      [ "${hlp:0:1}" == "/" ] && run=`echo ${hlp:1} | rev`
      echo "b2save -s $run"
      if [ -d $run ] && [ ! -z "$(ls -A "$run")" ]
      then
        if [ -d "$run.$ext" ]
        then
          echo "rm -rf $run.$ext"
	  rm -rf "$run"."$ext"
        fi
        echo "mkdir $run.$ext"
        mkdir "$run"."$ext"
	#Add extra files here
	echo "cd $run" && cd $run
        SAVE_LD=`ls ld_tg_* 2>/dev/null`
        SAVE_FP=`ls fp_tg_* 2>/dev/null`
        SAVE_PP=`ls peak_power* 2>/dev/null`
        SAVE_TRC=`ls -lt trc.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
        SAVE_TRG=`ls -lt trg.* 2>/dev/null | head -1 | rev | cut -f 1 -d " " | rev`
	SAVE_FILES="$SAVE_FILES_BASE $SAVE_LD $SAVE_FP $SAVE_PP $SAVE_TRC $SAVE_TRG"
	echo "cd ../" && cd ../
        for f in $SAVE_FILES; do {
          [ -f "$run/$f" ] && echo "cp -rf $run/$f $run.$ext/$f" && cp -rf "$run"/"$f" "$run"."$ext"/"$f"
          if [ ! -s "$run.$ext/$f" ]
          then
            echo "warning: $f either absent or empty"
          fi
        }; done
        for fd in $SAVE_DIR; do {
          [ -d "$run/$fd" ] && echo "cp -rf $run/$fd $run.$ext/" && cp -rf "$run"/"$fd" "$run"."$ext"/
          if [ ! -d "$run.$ext/$fd" ]
          then
            echo "warning: $fd is absent"
	  else
            if [ -z "$(ls -A "$run.$ext/$fd")" ]
            then
              echo "warning: $fd is empty"
	    fi
          fi
        }; done
      else
        echo "$run directory does not exist or empty, nothing to do"
      fi
      }; done
    }
  }

} || {

[ $mode == "c" ] && {

  [ -f "$SCR_MARK" ] && echo "$SCR_MARK present, workspace already exists?" && exit 1
  [ ! -f "$RUNCHK" ] && echo "no $RUNCHK, not a run directory?" && exit 1
  [ ! -d "$BRUN" ] && echo "no $BRUN directory detected, nothing to do" && exit 1
  [ -z "$(ls -A "$BRUN")" ] && echo "$BRUN directory empty, nothing to do" && exit 1

  echo "setting up worksape at $DW_DIR"
  echo "$DW_DIR" >$SCR_MARK
  echo "mkdir $DW_DIR"
  mkdir "$DW_DIR"
  echo "mkdir $DW_DIR/$BR"
  mkdir "$DW_DIR"/"$BR"
  for l in $BSR_LINKS; do {
    [ -f "$BRUN/$l" ] && echo "ln -sf $BRUN/$l $DW_DIR/$BR/$l" && ln -sf "$BRUN"/"$l" "$DW_DIR"/"$BR"/"$l"
    if [ ! -s "$DW_DIR/$BR/$l" ]
    then
      echo "warning: $l either absent or empty"
    else
      echo "gtfl -t $DW_DIR/$BR/$l"
      gtfl -t "$DW_DIR"/"$BR"/"$l"
    fi
    }; done
  ( echo "correcting timestamps" && cd "$DW_DIR" && correct_baserun_timestamps )
  echo "mkdir $DW_DIR/$RRUN"
  mkdir $DW_DIR/$RRUN
  echo "$CURRENT_DIR" >$DW_DIR/$SRC_MARK
  echo "$CURRENT_DIR" >$DW_DIR/$RRUN/$SRC_MARK
  echo "$CURRENT_DIR" >$DW_DIR/$BR/$SRC_MARK
  for f in $SCR_FILES; do {
    [ -f "./$f" ] && echo "cp -rf ./$f $DW_DIR/$RRUN/$f" && cp -rf ./"$f" "$DW_DIR"/"$RRUN"/"$f"
    if [ ! -s "$DW_DIR/$RRUN/$f" ]
    then
      echo "warning: $f either absent or empty"
    fi
    }; done
  for l in $SCR_LINKS; do {
    [ -f "./$l" ] && echo "ln -sf $CURRENT_DIR/$l $DW_DIR/$RRUN/$l" && ln -sf "$CURRENT_DIR"/"$l" "$DW_DIR"/"$RRUN"/"$l"
    if [ ! -s "$DW_DIR/$RRUN/$l" ]
    then
      echo "warning: $l either absent or empty"
    else
      echo "gtfl -t $DW_DIR/$RRUN/$l"
      gtfl -t "$DW_DIR"/"$RRUN"/"$l"
    fi
    }; done
  for fd in $SCR_DIR; do {
    [ -d "./$fd" ] && echo "cp -rf ./$fd $DW_DIR/$RRUN/" && cp -rf ./"$fd" "$DW_DIR"/"$RRUN"/"$fd"
    if [ ! -d "$DW_DIR/$RRUN/$fd" ]
    then
      echo "warning: $fd is absent"
    else
      if [ -z "$(ls -A "$DW_DIR/$RRUN/$fd")" ]
      then
        echo "warning: $fd is empty"
      fi
    fi
    }; done
  ( echo "setting eirene links" && cd "$DW_DIR"/"$RRUN" && setup_baserun_eirene_links )
  for tf in $SCR_TOP; do {
    [ -f "../$tf" ] && echo "cp -rf ../$tf $DW_DIR/$f" && cp -rf ../"$tf" "$DW_DIR"/"$tf"
    if [ ! -s "$DW_DIR/$tf" ]
    then
      echo "warning: $f either absent or empty"
    fi
    }; done
  }

} || {

[ $mode == "g" ] && {

  [ ! -f "$SCR_MARK" ] && echo "no $SCR_MARK present, workspace doesn't exists?" && exit 1

  echo "pulling files from $SCR_MARK/$RRUN"
  for f in $SRC_FILES; do {
    if [ ! -s "$DW_DIR/$RRUN/$f" ]
    then
      echo "warning: $f either absent or empty"
    else
      echo "cp -rf $DW_DIR/$RRUN/$f ./$f" && cp -rf "$DW_DIR"/"$RRUN"/"$f" ./"$f"
    fi
    }; done
  for fd in $SRC_DIR; do {
    if [ ! -d "$DW_DIR/$RRUN/$fd" ]
    then
      echo "warning: $fd is absent"
    else
      if [ -z "$(ls -A "$DW_DIR/$RRUN/$fd")" ]
      then
        echo "warning: $fd is empty"
      else
        echo "cp -rf $DW_DIR/$RRUN/$fd ./$fd" && rm -rf "$fd" && cp -rf "$DW_DIR"/"$RRUN"/"$fd" .
      fi
    fi
    }; done
  }

} || {

[ $mode == "r" ] && {

  [ ! -f "$SCR_MARK" ] && echo "no $SCR_MARK present, workspace doesn't exists?" && exit 1

  echo "cleaning workspace $DW_DIR"
  echo "rm -rf $DW_DIR"
  rm -rf "$DW_DIR"
  rm -rf "$SCR_MARK"
  }
}
