#! /bin/tcsh -f
set datapath=`echo $PWD/ | sed -e "s|$SOLPSTOP||" -e 's|[^/]*/|../|g' -e 's|$|modules/Eirene/Database|'`
if (${COMPILER} == "HP") then
  set filestem="ftn"
else
  set filestem="fort."
endif
if (! -s ${datapath}/PHOTON) then
  set datapath=`canonical $SOLPSTOP`/modules/Eirene/Database
  if (! -s ${datapath}/PHOTON) then
    set datapath=$SOLPSTOP/modules/Eirene/Database
  endif
endif
if ("X$1X" == "X-rX") then
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/amjuel.tex` AMJUEL
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/h2vibr.tex` H2VIBR
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/hydhel.tex` HYDHEL
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/methane.tex` METHANE
  ln -sf `climb_and_look_for -r modules/Eirene/Database/AMdata/ammoniaex.tex` AMMONX
  ln -sf `climb_and_look_for -r modules/Eirene/Database/PHOTON`
  ln -sf `climb_and_look_for -r modules/Eirene/Database/Surfacedata/SPUTER`
  ln -sf `climb_and_look_for -r modules/Eirene/Database/Surfacedata/TRIM/trim.dat` "$filestem"21
  ln -sf `climb_and_look_for -r modules/Eirene/Database/Surfacedata/TRIM/marlow.dat` "$filestem"22
else
  ln -sf ${datapath}/AMdata/amjuel.tex AMJUEL
  ln -sf ${datapath}/AMdata/h2vibr.tex H2VIBR
  ln -sf ${datapath}/AMdata/hydhel.tex HYDHEL
  ln -sf ${datapath}/AMdata/methane.tex METHANE
  ln -sf ${datapath}/AMdata/ammoniaex.tex AMMONX
  ln -sf ${datapath}/PHOTON
  ln -sf ${datapath}/Surfacedata/SPUTER
  ln -sf ${datapath}/Surfacedata/TRIM/trim.dat "$filestem"21
  ln -sf ${datapath}/Surfacedata/TRIM/marlow.dat "$filestem"22
endif

# ===================================================
# Eirene main input file handling - Formatted variant
#
# Look for input.dat (input.eir) in standard locations
if (! -s input.dat) then
  if (-s ../baserun/input.dat) then
    ln -s ../baserun/input.dat .
  else if (-s input.eir) then
    ln -s input.eir input.dat
    echo "Creating a link between input.eir and input.dat"
  else if (-s ../baserun/input.eir) then
   ln -s ../baserun/input.eir input.dat
   echo "Creating a link between ../baserun/input.eir and input.dat"
  else
    set inputfile=`climb_and_look_for input.dat`
    if (-s $inputfile) then
      ln -s $inputfile .
    else
      set inputfile=`climb_and_look_for input.eir`
      if (-s $inputfile) then
        ln -s $inputfile input.dat
        echo "Creating a link between $inputfile and input.dat"
      else
        echo "Warning: no input.dat found!"
      endif
    endif
  endif
endif
# Update the fort.1 link to point to input.dat
if (-s input.dat) then
  set fort1_target=`readlink "$filestem"1`
  if ("$fort1_target" != "input.dat") then
    if ( (-e "$filestem"1) && (! -l "$filestem"1) ) then
      echo "Warning: Unable to select Eirene input, ${filestem}1 exists but not a link!"
      echo "  - Please remove ${filestem}1 and run this script again."
    else
      ln -sf input.dat "$filestem"1
      echo "Selected FORMATTED Eirene input (${filestem}1 -> input.dat)."
      if ("$fort1_target" == "eirene.input.json") then
        echo "Warning: Changes in eirene.input.json not applied to input.dat will be lost on the next simulation run."
      endif
    endif
  endif
endif
# ===================================================

if (! -s "$filestem"33) then
  if (-s ../TRIANG/"$filestem"33) then
    ln -s ../TRIANG/"$filestem"33 .
    ln -s ../TRIANG/"$filestem"34 .
    ln -s ../TRIANG/"$filestem"35 .
  else if (-s ../baserun/"$filestem"33) then
    ln -s ../baserun/"$filestem"33 .
    ln -s ../baserun/"$filestem"34 .
    ln -s ../baserun/"$filestem"35 .
  endif
endif
if (! -s mesh.extra) then
  if (-s ../baserun/mesh.extra) then
    ln -s ../baserun/mesh.extra .
  else
    set meshxtra=`climb_and_look_for mesh.extra`
    if (-s $meshxtra) then
      ln -s $meshxtra .
    endif
  endif
endif
if (! -s param.dg) then
  if (-s ../baserun/param.dg) then
    ln -s ../baserun/param.dg .
  else
    set paramdg=`climb_and_look_for param.dg`
    if (-s $paramdg) then
      ln -s $paramdg .
    endif
  endif
endif
if (! -d tracing) mkdir tracing
if (! -d batch_av) mkdir batch_av
if (! -d run_av) mkdir run_av
