#! /usr/bin/env tcsh

cd $SOLPSTOP
set repo="SOLPS-ITER"

if ( $?SOLPS_ORNL_BRANCH ) then
  set ornl_branch = $SOLPS_ORNL_BRANCH
else
  set ornl_branch = ornl-multisystem-setup
endif

echo "Switching to SOLPS-ITER ORNL branch ${ornl_branch}"
git fetch --prune
git checkout ${ornl_branch} && echo "Checked out SOLPS-ITER ORNL branch ${ornl_branch}" || goto branch
git submodule init
git submodule update || git -c submodule.ADAS.update=none submodule update
git pull && goto b25 || goto local

b25:
  echo "Updating B2.5"
  cd $SOLPSTOP/modules/B2.5
  set repo="B2.5"
  git fetch --prune
  git checkout feature/wg-release && echo "Checked out B2.5 WG-release branch" || goto branch
  git pull && goto Eirene || goto local

Eirene:
  echo "Updating Eirene"
  cd $SOLPSTOP/modules/Eirene
  set repo="Eirene"
  git fetch --prune
  git checkout SOLPS_develop && echo "Checked out Eirene SOLPS_develop branch" || goto branch
  git pull && goto Carre || goto local

Carre:
  echo "Updating Carre"
  cd $SOLPSTOP/modules/Carre
  set repo="Carre"
  git fetch --prune
  git checkout develop && echo "Checked out Carre develop branch" || goto branch
  git pull && goto Carre2 || goto local

Carre2:
  echo "Updating Carre2"
  if (! -d $SOLPSTOP/modules/Carre2) then
    git clone git@github.com:iterorganization/CARRE.git $SOLPSTOP/modules/Carre2
    git submodule init
    git submodule update
  endif
  cd $SOLPSTOP/modules/Carre2
  set repo="Carre2"
  git fetch --prune
  git checkout feature/Carre2_wg_release && echo "Checked out Carre2 WG-release branch" || goto branch
  git pull && goto DivGeo || goto local

DivGeo:
  echo "Updating DivGeo"
  cd $SOLPSTOP/modules/DivGeo
  set repo="DivGeo"
  git fetch --prune
  git checkout feature/wg_release && echo "Checked out DivGeo WG-release branch" || goto branch
  git pull && goto ADAS || goto local

ADAS:
  echo "Updating ADAS"
  if (-s $SOLPSTOP/modules/adas/.gitattributes) then
    cd $SOLPSTOP/modules/adas
    set repo="ADAS"
    git fetch --prune
    git checkout develop && echo "Checked out ADAS develop branch" || goto branch
    git pull && goto compile || goto local
  else
    $SOLPSTOP/scripts/fetch_adas_datafiles && goto compile || exit
  endif

branch:
  echo "You are not on the expected branch for "$repo"."

local:
  echo "In your "$repo" copy:"
  echo "You have local files under version control which"
  echo "would cause a conflict during the update."
  echo "Please modify, delete, rename, stash these files or"
  echo "commit them to a local branch before proceeding with the update."
  git status
  exit

compile:
  cd $SOLPSTOP
  rehash
  ${MAKE} VERSION
  ${MAKE} listobj listobj_debug
  ${MAKE} depend depend_debug
  ${MAKE} tags
  ${MAKE} solps MAKE_OPTIONS=-j8
