#! /usr/bin/env tcsh

cd $SOLPSTOP
echo "Switching to SOLPS-ITER WG-release branch"
set repo="SOLPS-ITER"
git fetch --prune
git checkout feature/wg-release && echo "Checked out SOLPS-ITER WG-release branch" || goto branch
git submodule init
set adas_url = `git config -f .gitmodules --get submodule.ADAS.url`
set adas_available = 0
if ("$adas_url" != "") then
  env GIT_SSH_COMMAND="ssh -o BatchMode=yes -o ConnectTimeout=5 -o ConnectionAttempts=1" git ls-remote --exit-code "$adas_url" HEAD >& /dev/null
  if ($status == 0) set adas_available = 1
endif
if ($adas_available) then
  git submodule update
else
  echo "Skipping ADAS submodule update; using local ADAS datafile fallback."
  git -c submodule.ADAS.update=none submodule update
endif
git pull && goto b25 || goto local

b25:
  echo "Updating B2.5"
  cd $SOLPSTOP/modules/B2.5
  set repo="B2.5"
  git fetch --prune
  git checkout feature/wg-release && echo "Checked out B2.5 WG-release branch" || goto branch
  git pull && goto Eirene || goto local

Eirene:
  echo "Updating Eirene"
  cd $SOLPSTOP/modules/Eirene
  set repo="Eirene"
  git fetch --prune
  git checkout SOLPS_develop && echo "Checked out Eirene SOLPS_develop branch" || goto branch
  git pull && goto Carre || goto local

Carre:
  echo "Updating Carre"
  cd $SOLPSTOP/modules/Carre
  set repo="Carre"
  git fetch --prune
  git checkout develop && echo "Checked out Carre develop branch" || goto branch
  git pull && goto Carre2 || goto local

Carre2:
  echo "Updating Carre2"
  if (! -d $SOLPSTOP/modules/Carre2) then
    git clone git@github.com:iterorganization/CARRE.git $SOLPSTOP/modules/Carre2
    git submodule init
    git submodule update
  endif
  cd $SOLPSTOP/modules/Carre2
  set repo="Carre2"
  git fetch --prune
  git checkout feature/Carre2_wg_release && echo "Checked out Carre2 WG-release branch" || goto branch
  git pull && goto DivGeo || goto local

DivGeo:
  echo "Updating DivGeo"
  cd $SOLPSTOP/modules/DivGeo
  set repo="DivGeo"
  git fetch --prune
  git checkout feature/wg_release && echo "Checked out DivGeo WG-release branch" || goto branch
  git pull && goto ADAS || goto local

ADAS:
  echo "Updating ADAS"
  if (-s $SOLPSTOP/modules/adas/.gitattributes) then
    cd $SOLPSTOP/modules/adas
    set repo="ADAS"
    git fetch --prune
    git checkout develop && echo "Checked out ADAS develop branch" || goto branch
    git pull && goto compile || goto local
  else
    $SOLPSTOP/scripts/fetch_adas_datafiles && goto compile || exit
  endif

branch:
  echo "You are not on the WG-release branch."

local:
  echo "In your "$repo" copy:"
  echo "You have local files under version control which"
  echo "would cause a conflict during the update."
  echo "Please modify, delete, rename, stash these files or"
  echo "commit them to a local branch before proceeding with the update."
  git status
  exit

compile:
  cd $SOLPSTOP
  rehash
  ${MAKE} VERSION
  ${MAKE} listobj listobj_debug
  ${MAKE} depend depend_debug
  ${MAKE} tags
  ${MAKE} solps MAKE_OPTIONS=-j8
