# Command file for get_series.py (similar to last_2d.cmd)
#
#===============================================================================
#  USAGE:
#                Syntax (mandatory): " A : B : C : D : E "
#
#  A  - text, name of the file containing the original data without extension
#       (i.e b2time, sepdata etc)
#
#  B  - text, name of the desired quantity as it stands in the raw output
#       (for .trc files and single dimension quantities in .nc files
#       corresponds to the quantity names directly, whereas multidimensional
#       data from .nc files are unpacked via adding specific suffixes that
#       and the quantity names should be looked up in the last_2d.py driver)
#
#  C  - real, scaling factor, original quantity value will be scaled with it
#
#  D  - text, name under which the quantity will appear in the formatted output
#       (if blank the original quantity name (field B) will be used)
#
#  E  - text, the units of the resulting quantity value (after scaling), will
#       be shown in brackets after the name (if blank "N/A" will be added to
#       distinguish between lack of units provided and a.u. quantities)
#==============================================================================

sepdata  : ne_sep      : 1. : ne_sep     : m^-3
sepdata  : Te_sep      : 1. : Te_sep     : eV
sepdata  : Ti_sep      : 1. : Ti_sep     : eV
sepdata  : Zef_sep     : 1. : Zeff_sep   : a.u.
sepdata  : nr_sep_H    : 1. : nr_sep_H   : a.u.
sepdata  : nr_sep_D    : 1. : nr_sep_D   : a.u.
sepdata  : nr_sep_T    : 1. : nr_sep_T   : a.u.
sepdata  : nr_sep_He   : 1. : nr_sep_He  : a.u.
sepdata  : nr_sep_Li   : 1. : nr_sep_Li  : a.u.
sepdata  : nr_sep_Be   : 1. : nr_sep_Be  : a.u.
sepdata  : nr_sep_B    : 1. : nr_sep_B   : a.u.
sepdata  : nr_sep_C    : 1. : nr_sep_C   : a.u.
sepdata  : nr_sep_N    : 1. : nr_sep_N   : a.u.
sepdata  : nr_sep_O    : 1. : nr_sep_O   : a.u.
sepdata  : nr_sep_Ne   : 1. : nr_sep_Ne  : a.u.
sepdata  : nr_sep_Ar   : 1. : nr_sep_Ar  : a.u.
sepdata  : nr_sep_Fe   : 1. : nr_sep_Fe  : a.u.
sepdata  : nr_sep_W    : 1. : nr_sep_W   : a.u.

user     : Pneu_PFR    : 1. : p_neut_av : Pa
user     : Pneu_PFi    : 1. : p_neut_i  : Pa
user     : Pneu_PFo    : 1. : p_neut_o  : Pa

user     : pk_pwr_i   : 1.e-6 : qpk_shp_i  : MW/m^2
user     : pk_pwr_o   : 1.e-6 : qpk_shp_o  : MW/m^2
user     : pk_pw_iu   : 1.e-6 : qpk_shp_iu : MW/m^2
user     : pk_pw_ou   : 1.e-6 : qpk_shp_ou : MW/m^2
user     : pk_ppf_w   : 1.e-6 : qpk_par_w  : MW/m^2
user     : isatt_il   : 1.e-6 : I_sat_i    : MA
user     : isatt_ol   : 1.e-6 : I_sat_o    : MA
user     : isatt_iu   : 1.e-6 : I_sat_iu   : MA
user     : isatt_ou   : 1.e-6 : I_sat_ou   : MA

user     : Sp_DT     : 1. : Sp_DT     : m^3s^-1
user     : Sp_He     : 1. : Sp_He     : m^3s^-1
user     : DT_thrpt  : 1. : DT_thrpt  : Pa*m^3s^-1
user     : He_thrpt  : 1. : He_thrpt  : Pa*m^3s^-1
user     : Area_pump : 1. : A_pump    : m^2
user     : n_H_pump  : 1. : n_H_pump  : m^-3
user     : T_H_pump  : 1. : T_H_pump  : eV
user     : p_H_pump  : 1. : P_H_pump  : Pa
user     : n_D_pump  : 1. : n_D_pump  : m^-3
user     : T_D_pump  : 1. : T_D_pump  : eV
user     : p_D_pump  : 1. : P_D_pump  : Pa
user     : n_T_pump  : 1. : n_T_pump  : m^-3
user     : T_T_pump  : 1. : T_T_pump  : eV
user     : p_T_pump  : 1. : P_T_pump  : Pa
user     : n_H2_pump : 1. : n_H2_pump : m^-3
user     : T_H2_pump : 1. : T_H2_pump : eV
user     : p_H2_pump : 1. : P_H2_pump : Pa
user     : n_D2_pump : 1. : n_D2_pump : m^-3
user     : T_D2_pump : 1. : T_D2_pump : eV
user     : p_D2_pump : 1. : P_D2_pump : Pa
user     : n_T2_pump : 1. : n_T2_pump : m^-3
user     : T_T2_pump : 1. : T_T2_pump : eV
user     : p_T2_pump : 1. : P_T2_pump : Pa
user     : n_He_pump : 1. : n_He_pump : m^-3
user     : T_He_pump : 1. : T_He_pump : eV
user     : p_He_pump : 1. : P_He_pump : Pa

b2time   : nesepi_l : 1.    : ne_SP_i    : m^-3
b2time   : nesepa_l : 1.    : ne_SP_o    : m^-3
b2time   : nesepi_u : 1.    : ne_SP_iu   : m^-3
b2time   : nesepa_u : 1.    : ne_SP_ou   : m^-3
b2time   : nemxip_l : 1.    : ne_max_i   : m^-3
b2time   : nemxap_l : 1.    : ne_max_o   : m^-3
b2time   : nemxip_u : 1.    : ne_max_iu  : m^-3
b2time   : nemxap_u : 1.    : ne_max_ou  : m^-3
b2time   : tesepi_l : 1.    : Te_SP_i    : eV
b2time   : tesepa_l : 1.    : Te_SP_o    : eV
b2time   : tesepi_u : 1.    : Te_SP_u    : eV
b2time   : tesepa_u : 1.    : Te_SP_u    : eV
b2time   : temxip_l : 1.    : Te_max_i   : eV
b2time   : temxap_l : 1.    : Te_max_o   : eV
b2time   : temxip_u : 1.    : Te_max_iu  : eV
b2time   : temxap_u : 1.    : Te_max_ou  : eV
b2time   : tisepi_l : 1.    : Ti_SP_i    : eV
b2time   : tisepa_l : 1.    : Ti_SP_o    : eV
b2time   : tisepi_u : 1.    : Ti_SP_i    : eV
b2time   : tisepa_u : 1.    : Ti_SP_o    : eV
b2time   : timxip_l : 1.    : Ti_max_i   : eV
b2time   : timxap_l : 1.    : Ti_max_o   : eV
b2time   : timxip_u : 1.    : Ti_max_iu  : eV
b2time   : timxap_u : 1.    : Ti_max_ou  : eV
b2time   : posepi_l : 1.    : Pot_SP_i   : V
b2time   : posepa_l : 1.    : Pot_SP_o   : V
b2time   : posepi_u : 1.    : Pot_SP_iu  : V
b2time   : posepa_u : 1.    : Pot_SP_ou  : V
b2time   : pomxip_l : 1.    : Pot_max_i  : V
b2time   : pomxap_l : 1.    : Pot_max_o  : V
b2time   : pomxip_u : 1.    : Pot_max_iu : V
b2time   : pomxap_u : 1.    : Pot_max_ou : V

blne    : tot_core   : 1.e-6 : P_core      : MW
sepdata : Qt_sep     : 1.e-6 : P_sep       : MW
blne    : tot_targ   : 1.e-6 : Q_trg       : MW
blne    : tot_wall   : 1.e-6 : Q_wall      : MW
blne    : tot_rad    : 1.e-6 : Q_tot_rad   : MW
blne    : ntrl_rad   : 1.e-6 : Q_neut_rad  : MW
blne    : imp_rad    : 1.e-6 : Q_imp_rad   : MW
blne    : imp_rad_He : 1.e-6 : Q_imp_He    : MW
blne    : imp_rad_Li : 1.e-6 : Q_imp_Li    : MW
blne    : imp_rad_Be : 1.e-6 : Q_imp_Be    : MW
blne    : imp_rad_B  : 1.e-6 : Q_imp_B     : MW
blne    : imp_rad_C  : 1.e-6 : Q_imp_C     : MW
blne    : imp_rad_N  : 1.e-6 : Q_imp_N     : MW
blne    : imp_rad_O  : 1.e-6 : Q_imp_O     : MW
blne    : imp_rad_Ne : 1.e-6 : Q_imp_Ne    : MW
blne    : imp_rad_Ar : 1.e-6 : Q_imp_Ar    : MW
blne    : imp_rad_Fe : 1.e-6 : Q_imp_Fe    : MW
blne    : imp_rad_W  : 1.e-6 : Q_imp_W     : MW

b2time  : feexip_l : -1.e-6 : P_div_e_il  : MW
b2time  : feixip_l : -1.e-6 : P_div_i_il  : MW
b2time  : fetxip_l : -1.e-6 : P_div_t_il  : MW
b2time  : feexap_l :  1.e-6 : P_div_e_ol  : MW
b2time  : feixap_l :  1.e-6 : P_div_i_ol  : MW
b2time  : fetxap_l :  1.e-6 : P_div_t_ol  : MW
b2time  : feexip_u : -1.e-6 : P_div_e_iu  : MW
b2time  : feixip_u : -1.e-6 : P_div_i_iu  : MW
b2time  : fetxip_u : -1.e-6 : P_div_t_iu  : MW
b2time  : feexap_u :  1.e-6 : P_div_e_ou  : MW
b2time  : feixap_u :  1.e-6 : P_div_i_ou  : MW
b2time  : fetxap_u :  1.e-6 : P_div_t_ou  : MW

blne    : pwr_totl_il  : 1.e-6 : Q_tot_trg_il   : MW
blne    : pwr_plsm_il  : 1.e-6 : Q_plsm_trg_il  : MW
blne    : pwr_neut_il  : 1.e-6 : Q_neut_trg_il  : MW
blne    : pwr_ionz_il  : 1.e-6 : Q_ionz_trg_il  : MW
blne    : pwr_diss_il  : 1.e-6 : Q_diss_trg_il  : MW

blne    : pwr_totl_ol  : 1.e-6 : Q_tot_trg_ol   : MW
blne    : pwr_plsm_ol  : 1.e-6 : Q_plsm_trg_ol  : MW
blne    : pwr_neut_ol  : 1.e-6 : Q_neut_trg_ol  : MW
blne    : pwr_ionz_ol  : 1.e-6 : Q_ionz_trg_ol  : MW
blne    : pwr_diss_ol  : 1.e-6 : Q_diss_trg_ol  : MW

blne    : pwr_totl_iu  : 1.e-6 : Q_tot_trg_iu   : MW
blne    : pwr_plsm_iu  : 1.e-6 : Q_plsm_trg_iu  : MW
blne    : pwr_neut_iu  : 1.e-6 : Q_neut_trg_iu  : MW
blne    : pwr_ionz_iu  : 1.e-6 : Q_ionz_trg_iu  : MW
blne    : pwr_diss_iu  : 1.e-6 : Q_diss_trg_iu  : MW

blne    : pwr_totl_ou  : 1.e-6 : Q_tot_trg_ou   : MW
blne    : pwr_plsm_ou  : 1.e-6 : Q_plsm_trg_ou  : MW
blne    : pwr_neut_ou  : 1.e-6 : Q_neut_trg_ou  : MW
blne    : pwr_ionz_ou  : 1.e-6 : Q_ionz_trg_ou  : MW
blne    : pwr_diss_ou  : 1.e-6 : Q_diss_trg_ou  : MW

blne    : pwr_totl_wl  : 1.e-6 : Q_tot_trg_wl   : MW
blne    : pwr_plsm_wl  : 1.e-6 : Q_plsm_trg_wl  : MW
blne    : pwr_neut_wl  : 1.e-6 : Q_neut_trg_wl  : MW
blne    : pwr_ionz_wl  : 1.e-6 : Q_ionz_trg_wl  : MW
blne    : pwr_diss_wl  : 1.e-6 : Q_diss_trg_wl  : MW

blnn    : ion_core_H   : 1. : ion_core_H  : s^-1
blnn    : ntr_core_H   : 1. : ntr_core_H  : s^-1
blnn    : ion_targ_H   : 1. : ion_targ_H  : s^-1
blnn    : ntr_targ_H   : 1. : ntr_targ_H  : s^-1
blnn    : ion_wall_H   : 1. : ion_wall_H  : s^-1
blnn    : ntr_wall_H   : 1. : ntr_wall_H  : s^-1
blnn    : ntr_puff_H   : 1. : ntr_puff_H  : s^-1
blnn    : flux_tot_H   : 1. : tot_flux_H  : s^-1
blnn    : flx_d/dt_H   : 1. : dN/dt_H     : s^-1
blnn    : flux_bln_H   : 1. : err_totl_H  : s^-1
blnn    : ion_core_D   : 1. : ion_core_D  : s^-1
blnn    : ntr_core_D   : 1. : ntr_core_D  : s^-1
blnn    : ion_targ_D   : 1. : ion_targ_D  : s^-1
blnn    : ntr_targ_D   : 1. : ntr_targ_D  : s^-1
blnn    : ion_wall_D   : 1. : ion_wall_D  : s^-1
blnn    : ntr_wall_D   : 1. : ntr_wall_D  : s^-1
blnn    : ntr_puff_D   : 1. : ntr_puff_D  : s^-1
blnn    : flux_tot_D   : 1. : tot_flux_D  : s^-1
blnn    : flx_d/dt_D   : 1. : dN/dt_D     : s^-1
blnn    : flux_bln_D   : 1. : err_totl_D  : s^-1
blnn    : ion_core_T   : 1. : ion_core_T  : s^-1
blnn    : ntr_core_T   : 1. : ntr_core_T  : s^-1
blnn    : ion_targ_T   : 1. : ion_targ_T  : s^-1
blnn    : ntr_targ_T   : 1. : ntr_targ_T  : s^-1
blnn    : ion_wall_T   : 1. : ion_wall_T  : s^-1
blnn    : ntr_wall_T   : 1. : ntr_wall_T  : s^-1
blnn    : ntr_puff_T   : 1. : ntr_puff_T  : s^-1
blnn    : flux_tot_T   : 1. : tot_flux_T  : s^-1
blnn    : flx_d/dt_T   : 1. : dN/dt_T     : s^-1
blnn    : flux_bln_T   : 1. : err_totl_T  : s^-1
blnn    : ion_core_He  : 1. : ion_core_He : s^-1
blnn    : ntr_core_He  : 1. : ntr_core_He : s^-1
blnn    : ion_targ_He  : 1. : ion_targ_He : s^-1
blnn    : ntr_targ_He  : 1. : ntr_targ_He : s^-1
blnn    : ion_wall_He  : 1. : ion_wall_He : s^-1
blnn    : ntr_wall_He  : 1. : ntr_wall_He : s^-1
blnn    : ntr_puff_He  : 1. : ntr_puff_He : s^-1
blnn    : flux_tot_He  : 1. : tot_flux_He : s^-1
blnn    : flx_d/dt_He  : 1. : dN/dt_He    : s^-1
blnn    : flux_bln_He  : 1. : err_totl_He : s^-1
blnn    : ion_core_Li  : 1. : ion_core_Li : s^-1
blnn    : ntr_core_Li  : 1. : ntr_core_Li : s^-1
blnn    : ion_targ_Li  : 1. : ion_targ_Li : s^-1
blnn    : ntr_targ_Li  : 1. : ntr_targ_Li : s^-1
blnn    : ion_wall_Li  : 1. : ion_wall_Li : s^-1
blnn    : ntr_wall_Li  : 1. : ntr_wall_Li : s^-1
blnn    : ntr_puff_Li  : 1. : ntr_puff_Li : s^-1
blnn    : flux_tot_Li  : 1. : tot_flux_Li : s^-1
blnn    : flx_d/dt_Li  : 1. : dN/dt_Li    : s^-1
blnn    : flux_bln_Li  : 1. : err_totl_Li : s^-1
blnn    : ion_core_Be  : 1. : ion_core_Be : s^-1
blnn    : ntr_core_Be  : 1. : ntr_core_Be : s^-1
blnn    : ion_targ_Be  : 1. : ion_targ_Be : s^-1
blnn    : ntr_targ_Be  : 1. : ntr_targ_Be : s^-1
blnn    : ion_wall_Be  : 1. : ion_wall_Be : s^-1
blnn    : ntr_wall_Be  : 1. : ntr_wall_Be : s^-1
blnn    : ntr_puff_Be  : 1. : ntr_puff_Be : s^-1
blnn    : flux_tot_Be  : 1. : tot_flux_Be : s^-1
blnn    : flx_d/dt_Be  : 1. : dN/dt_Be    : s^-1
blnn    : flux_bln_Be  : 1. : err_totl_Be : s^-1
blnn    : ion_core_B   : 1. : ion_core_B  : s^-1
blnn    : ntr_core_B   : 1. : ntr_core_B  : s^-1
blnn    : ion_targ_B   : 1. : ion_targ_B  : s^-1
blnn    : ntr_targ_B   : 1. : ntr_targ_B  : s^-1
blnn    : ion_wall_B   : 1. : ion_wall_B  : s^-1
blnn    : ntr_wall_B   : 1. : ntr_wall_B  : s^-1
blnn    : ntr_puff_B   : 1. : ntr_puff_B  : s^-1
blnn    : flux_tot_B   : 1. : tot_flux_B  : s^-1
blnn    : flx_d/dt_B   : 1. : dN/dt_B     : s^-1
blnn    : flux_bln_B   : 1. : err_totl_B  : s^-1
blnn    : ion_core_C   : 1. : ion_core_C  : s^-1
blnn    : ntr_core_C   : 1. : ntr_core_C  : s^-1
blnn    : ion_targ_C   : 1. : ion_targ_C  : s^-1
blnn    : ntr_targ_C   : 1. : ntr_targ_C  : s^-1
blnn    : ion_wall_C   : 1. : ion_wall_C  : s^-1
blnn    : ntr_wall_C   : 1. : ntr_wall_C  : s^-1
blnn    : ntr_puff_C   : 1. : ntr_puff_C  : s^-1
blnn    : flux_tot_C   : 1. : tot_flux_C  : s^-1
blnn    : flx_d/dt_C   : 1. : dN/dt_C     : s^-1
blnn    : flux_bln_C   : 1. : err_totl_C  : s^-1
blnn    : ion_core_N   : 1. : ion_core_N  : s^-1
blnn    : ntr_core_N   : 1. : ntr_core_N  : s^-1
blnn    : ion_targ_N   : 1. : ion_targ_N  : s^-1
blnn    : ntr_targ_N   : 1. : ntr_targ_N  : s^-1
blnn    : ion_wall_N   : 1. : ion_wall_N  : s^-1
blnn    : ntr_wall_N   : 1. : ntr_wall_N  : s^-1
blnn    : ntr_puff_N   : 1. : ntr_puff_N  : s^-1
blnn    : flux_tot_N   : 1. : tot_flux_N  : s^-1
blnn    : flx_d/dt_N   : 1. : dN/dt_N     : s^-1
blnn    : flux_bln_N   : 1. : err_totl_N  : s^-1
blnn    : ion_core_O   : 1. : ion_core_O  : s^-1
blnn    : ntr_core_O   : 1. : ntr_core_O  : s^-1
blnn    : ion_targ_O   : 1. : ion_targ_O  : s^-1
blnn    : ntr_targ_O   : 1. : ntr_targ_O  : s^-1
blnn    : ion_wall_O   : 1. : ion_wall_O  : s^-1
blnn    : ntr_wall_O   : 1. : ntr_wall_O  : s^-1
blnn    : ntr_puff_O   : 1. : ntr_puff_O  : s^-1
blnn    : flux_tot_O   : 1. : tot_flux_O  : s^-1
blnn    : flx_d/dt_O   : 1. : dN/dt_O     : s^-1
blnn    : flux_bln_O   : 1. : err_totl_O  : s^-1
blnn    : ion_core_Ne  : 1. : ion_core_Ne : s^-1
blnn    : ntr_core_Ne  : 1. : ntr_core_Ne : s^-1
blnn    : ion_targ_Ne  : 1. : ion_targ_Ne : s^-1
blnn    : ntr_targ_Ne  : 1. : ntr_targ_Ne : s^-1
blnn    : ion_wall_Ne  : 1. : ion_wall_Ne : s^-1
blnn    : ntr_wall_Ne  : 1. : ntr_wall_Ne : s^-1
blnn    : ntr_puff_Ne  : 1. : ntr_puff_Ne : s^-1
blnn    : flux_tot_Ne  : 1. : tot_flux_Ne : s^-1
blnn    : flx_d/dt_Ne  : 1. : dN/dt_Ne    : s^-1
blnn    : flux_bln_Ne  : 1. : err_totl_Ne : s^-1
blnn    : ion_core_Ar  : 1. : ion_core_Ar : s^-1
blnn    : ntr_core_Ar  : 1. : ntr_core_Ar : s^-1
blnn    : ion_targ_Ar  : 1. : ion_targ_Ar : s^-1
blnn    : ntr_targ_Ar  : 1. : ntr_targ_Ar : s^-1
blnn    : ion_wall_Ar  : 1. : ion_wall_Ar : s^-1
blnn    : ntr_wall_Ar  : 1. : ntr_wall_Ar : s^-1
blnn    : ntr_puff_Ar  : 1. : ntr_puff_Ar : s^-1
blnn    : flux_tot_Ar  : 1. : tot_flux_Ar : s^-1
blnn    : flx_d/dt_Ar  : 1. : dN/dt_Ar    : s^-1
blnn    : flux_bln_Ar  : 1. : err_totl_Ar : s^-1
blnn    : ion_core_Fe  : 1. : ion_core_Fe : s^-1
blnn    : ntr_core_Fe  : 1. : ntr_core_Fe : s^-1
blnn    : ion_targ_Fe  : 1. : ion_targ_Fe : s^-1
blnn    : ntr_targ_Fe  : 1. : ntr_targ_Fe : s^-1
blnn    : ion_wall_Fe  : 1. : ion_wall_Fe : s^-1
blnn    : ntr_wall_Fe  : 1. : ntr_wall_Fe : s^-1
blnn    : ntr_puff_Fe  : 1. : ntr_puff_Fe : s^-1
blnn    : flux_tot_Fe  : 1. : tot_flux_Fe : s^-1
blnn    : flx_d/dt_Fe  : 1. : dN/dt_Fe    : s^-1
blnn    : flux_bln_Fe  : 1. : err_totl_Fe : s^-1
blnn    : ion_core_W   : 1. : ion_core_W  : s^-1
blnn    : ntr_core_W   : 1. : ntr_core_W  : s^-1
blnn    : ion_targ_W   : 1. : ion_targ_W  : s^-1
blnn    : ntr_targ_W   : 1. : ntr_targ_W  : s^-1
blnn    : ion_wall_W   : 1. : ion_wall_W  : s^-1
blnn    : ntr_wall_W   : 1. : ntr_wall_W  : s^-1
blnn    : ntr_puff_W   : 1. : ntr_puff_W  : s^-1
blnn    : flux_tot_W   : 1. : tot_flux_W  : s^-1
blnn    : flx_d/dt_W   : 1. : dN/dt_W     : s^-1
blnn    : flux_bln_W   : 1. : err_totl_W  : s^-1

integral : SSNI_tot_H   : 1.        : SNI_tot_H  : s^-1
integral : SSNI_tot_D   : 1.        : SNI_tot_D  : s^-1
integral : SSNI_tot_T   : 1.        : SNI_tot_T  : s^-1
integral : SSNI_tot_He  : 1.        : SNI_tot_He : s^-1
integral : SSNI_tot_Li  : 1.        : SNI_tot_Li : s^-1
integral : SSNI_tot_Be  : 1.        : SNI_tot_Be : s^-1
integral : SSNI_tot_B   : 1.        : SNI_tot_B  : s^-1
integral : SSNI_tot_C   : 1.        : SNI_tot_C  : s^-1
integral : SSNI_tot_N   : 1.        : SNI_tot_N  : s^-1
integral : SSNI_tot_O   : 1.        : SNI_tot_O  : s^-1
integral : SSNI_tot_Ne  : 1.        : SNI_tot_Ne : s^-1
integral : SSNI_tot_Ar  : 1.        : SNI_tot_Ar : s^-1
integral : SSNI_tot_Fe  : 1.        : SNI_tot_Fe : s^-1
integral : SSNI_tot_W   : 1.        : SNI_tot_W  : s^-1
integral : SNI_rcmb     : 6.242e+18 : SNI_rcmb   : s^-1

integral : SSNIreg_01_H  : 1. : SNI_01_H   : s^-1
integral : SSNIreg_02_H  : 1. : SNI_02_H   : s^-1
integral : SSNIreg_03_H  : 1. : SNI_03_H   : s^-1
integral : SSNIreg_04_H  : 1. : SNI_04_H   : s^-1
integral : SSNIreg_05_H  : 1. : SNI_05_H   : s^-1
integral : SSNIreg_06_H  : 1. : SNI_06_H   : s^-1
integral : SSNIreg_07_H  : 1. : SNI_07_H   : s^-1
integral : SSNIreg_08_H  : 1. : SNI_08_H   : s^-1
integral : SSNIreg_01_D  : 1. : SNI_01_D   : s^-1
integral : SSNIreg_02_D  : 1. : SNI_02_D   : s^-1
integral : SSNIreg_03_D  : 1. : SNI_03_D   : s^-1
integral : SSNIreg_04_D  : 1. : SNI_04_D   : s^-1
integral : SSNIreg_05_D  : 1. : SNI_05_D   : s^-1
integral : SSNIreg_06_D  : 1. : SNI_06_D   : s^-1
integral : SSNIreg_07_D  : 1. : SNI_07_D   : s^-1
integral : SSNIreg_08_D  : 1. : SNI_08_D   : s^-1
integral : SSNIreg_01_T  : 1. : SNI_01_T   : s^-1
integral : SSNIreg_02_T  : 1. : SNI_02_T   : s^-1
integral : SSNIreg_03_T  : 1. : SNI_03_T   : s^-1
integral : SSNIreg_04_T  : 1. : SNI_04_T   : s^-1
integral : SSNIreg_05_T  : 1. : SNI_05_T   : s^-1
integral : SSNIreg_06_T  : 1. : SNI_06_T   : s^-1
integral : SSNIreg_07_T  : 1. : SNI_07_T   : s^-1
integral : SSNIreg_08_T  : 1. : SNI_08_T   : s^-1
integral : SSNIreg_01_He : 1. : SNI_01_He  : s^-1
integral : SSNIreg_02_He : 1. : SNI_02_He  : s^-1
integral : SSNIreg_03_He : 1. : SNI_03_He  : s^-1
integral : SSNIreg_04_He : 1. : SNI_04_He  : s^-1
integral : SSNIreg_05_He : 1. : SNI_05_He  : s^-1
integral : SSNIreg_06_He : 1. : SNI_06_He  : s^-1
integral : SSNIreg_07_He : 1. : SNI_07_He  : s^-1
integral : SSNIreg_08_He : 1. : SNI_08_He  : s^-1
integral : SSNIreg_01_Li : 1. : SNI_01_Li  : s^-1
integral : SSNIreg_02_Li : 1. : SNI_02_Li  : s^-1
integral : SSNIreg_03_Li : 1. : SNI_03_Li  : s^-1
integral : SSNIreg_04_Li : 1. : SNI_04_Li  : s^-1
integral : SSNIreg_05_Li : 1. : SNI_05_Li  : s^-1
integral : SSNIreg_06_Li : 1. : SNI_06_Li  : s^-1
integral : SSNIreg_07_Li : 1. : SNI_07_Li  : s^-1
integral : SSNIreg_08_Li : 1. : SNI_08_Li  : s^-1
integral : SSNIreg_01_Be : 1. : SNI_01_Be  : s^-1
integral : SSNIreg_02_Be : 1. : SNI_02_Be  : s^-1
integral : SSNIreg_03_Be : 1. : SNI_03_Be  : s^-1
integral : SSNIreg_04_Be : 1. : SNI_04_Be  : s^-1
integral : SSNIreg_05_Be : 1. : SNI_05_Be  : s^-1
integral : SSNIreg_06_Be : 1. : SNI_06_Be  : s^-1
integral : SSNIreg_07_Be : 1. : SNI_07_Be  : s^-1
integral : SSNIreg_08_Be : 1. : SNI_08_Be  : s^-1
integral : SSNIreg_01_B  : 1. : SNI_01_B   : s^-1
integral : SSNIreg_02_B  : 1. : SNI_02_B   : s^-1
integral : SSNIreg_03_B  : 1. : SNI_03_B   : s^-1
integral : SSNIreg_04_B  : 1. : SNI_04_B   : s^-1
integral : SSNIreg_05_B  : 1. : SNI_05_B   : s^-1
integral : SSNIreg_06_B  : 1. : SNI_06_B   : s^-1
integral : SSNIreg_07_B  : 1. : SNI_07_B   : s^-1
integral : SSNIreg_08_B  : 1. : SNI_08_B   : s^-1
integral : SSNIreg_01_C  : 1. : SNI_01_C   : s^-1
integral : SSNIreg_02_C  : 1. : SNI_02_C   : s^-1
integral : SSNIreg_03_C  : 1. : SNI_03_C   : s^-1
integral : SSNIreg_04_C  : 1. : SNI_04_C   : s^-1
integral : SSNIreg_05_C  : 1. : SNI_05_C   : s^-1
integral : SSNIreg_06_C  : 1. : SNI_06_C   : s^-1
integral : SSNIreg_07_C  : 1. : SNI_07_C   : s^-1
integral : SSNIreg_08_C  : 1. : SNI_08_C   : s^-1
integral : SSNIreg_01_N  : 1. : SNI_01_N   : s^-1
integral : SSNIreg_02_N  : 1. : SNI_02_N   : s^-1
integral : SSNIreg_03_N  : 1. : SNI_03_N   : s^-1
integral : SSNIreg_04_N  : 1. : SNI_04_N   : s^-1
integral : SSNIreg_05_N  : 1. : SNI_05_N   : s^-1
integral : SSNIreg_06_N  : 1. : SNI_06_N   : s^-1
integral : SSNIreg_07_N  : 1. : SNI_07_N   : s^-1
integral : SSNIreg_08_N  : 1. : SNI_08_N   : s^-1
integral : SSNIreg_01_O  : 1. : SNI_01_O   : s^-1
integral : SSNIreg_02_O  : 1. : SNI_02_O   : s^-1
integral : SSNIreg_03_O  : 1. : SNI_03_O   : s^-1
integral : SSNIreg_04_O  : 1. : SNI_04_O   : s^-1
integral : SSNIreg_05_O  : 1. : SNI_05_O   : s^-1
integral : SSNIreg_06_O  : 1. : SNI_06_O   : s^-1
integral : SSNIreg_07_O  : 1. : SNI_07_O   : s^-1
integral : SSNIreg_08_O  : 1. : SNI_08_O   : s^-1
integral : SSNIreg_01_Ne : 1. : SNI_01_Ne  : s^-1
integral : SSNIreg_02_Ne : 1. : SNI_02_Ne  : s^-1
integral : SSNIreg_03_Ne : 1. : SNI_03_Ne  : s^-1
integral : SSNIreg_04_Ne : 1. : SNI_04_Ne  : s^-1
integral : SSNIreg_05_Ne : 1. : SNI_05_Ne  : s^-1
integral : SSNIreg_06_Ne : 1. : SNI_06_Ne  : s^-1
integral : SSNIreg_07_Ne : 1. : SNI_07_Ne  : s^-1
integral : SSNIreg_08_Ne : 1. : SNI_08_Ne  : s^-1
integral : SSNIreg_01_Ar : 1. : SNI_01_Ar  : s^-1
integral : SSNIreg_02_Ar : 1. : SNI_02_Ar  : s^-1
integral : SSNIreg_03_Ar : 1. : SNI_03_Ar  : s^-1
integral : SSNIreg_04_Ar : 1. : SNI_04_Ar  : s^-1
integral : SSNIreg_05_Ar : 1. : SNI_05_Ar  : s^-1
integral : SSNIreg_06_Ar : 1. : SNI_06_Ar  : s^-1
integral : SSNIreg_07_Ar : 1. : SNI_07_Ar  : s^-1
integral : SSNIreg_08_Ar : 1. : SNI_08_Ar  : s^-1
integral : SSNIreg_01_Fe : 1. : SNI_01_Fe  : s^-1
integral : SSNIreg_02_Fe : 1. : SNI_02_Fe  : s^-1
integral : SSNIreg_03_Fe : 1. : SNI_03_Fe  : s^-1
integral : SSNIreg_04_Fe : 1. : SNI_04_Fe  : s^-1
integral : SSNIreg_05_Fe : 1. : SNI_05_Fe  : s^-1
integral : SSNIreg_06_Fe : 1. : SNI_06_Fe  : s^-1
integral : SSNIreg_07_Fe : 1. : SNI_07_Fe  : s^-1
integral : SSNIreg_08_Fe : 1. : SNI_08_Fe  : s^-1
integral : SSNIreg_01_W  : 1. : SNI_01_W   : s^-1
integral : SSNIreg_02_W  : 1. : SNI_02_W   : s^-1
integral : SSNIreg_03_W  : 1. : SNI_03_W   : s^-1
integral : SSNIreg_04_W  : 1. : SNI_04_W   : s^-1
integral : SSNIreg_05_W  : 1. : SNI_05_W   : s^-1
integral : SSNIreg_06_W  : 1. : SNI_06_W   : s^-1
integral : SSNIreg_07_W  : 1. : SNI_07_W   : s^-1
integral : SSNIreg_08_W  : 1. : SNI_08_W   : s^-1

integral : N_s_slt_H  : 1. : N_t_edge_H  : part.
integral : N_s_slt_D  : 1. : N_t_edge_D  : part.
integral : N_s_slt_T  : 1. : N_t_edge_T  : part.
integral : N_s_slt_He : 1. : N_t_edge_He : part.
integral : N_s_slt_Li : 1. : N_t_edge_Li : part.
integral : N_s_slt_Be : 1. : N_t_edge_Be : part.
integral : N_s_slt_B  : 1. : N_t_edge_B  : part.
integral : N_s_slt_C  : 1. : N_t_edge_C  : part.
integral : N_s_slt_N  : 1. : N_t_edge_N  : part.
integral : N_s_slt_O  : 1. : N_t_edge_O  : part.
integral : N_s_slt_Ne : 1. : N_t_edge_Ne : part.
integral : N_s_slt_Ar : 1. : N_t_edge_Ar : part.
integral : N_s_slt_Fe : 1. : N_t_edge_Fe : part.
integral : N_s_slt_W  : 1. : N_t_edge_W  : part.
integral : N_s_sla_H  : 1. : N_a_edge_H  : part.
integral : N_s_sla_D  : 1. : N_a_edge_D  : part.
integral : N_s_sla_T  : 1. : N_a_edge_T  : part.
integral : N_s_sla_He : 1. : N_a_edge_He : part.
integral : N_s_sla_Li : 1. : N_a_edge_Li : part.
integral : N_s_sla_Be : 1. : N_a_edge_Be : part.
integral : N_s_sla_B  : 1. : N_a_edge_B  : part.
integral : N_s_sla_C  : 1. : N_a_edge_C  : part.
integral : N_s_sla_N  : 1. : N_a_edge_N  : part.
integral : N_s_sla_O  : 1. : N_a_edge_O  : part.
integral : N_s_sla_Ne : 1. : N_a_edge_Ne : part.
integral : N_s_sla_Ar : 1. : N_a_edge_Ar : part.
integral : N_s_sla_W  : 1. : N_a_edge_W  : part.
integral : N_s_sli_H  : 1. : N_i_edge_H  : part.
integral : N_s_sli_D  : 1. : N_i_edge_D  : part.
integral : N_s_sli_T  : 1. : N_i_edge_T  : part.
integral : N_s_sli_He : 1. : N_i_edge_He : part.
integral : N_s_sli_Li : 1. : N_i_edge_Li : part.
integral : N_s_sli_Be : 1. : N_i_edge_Be : part.
integral : N_s_sli_B  : 1. : N_i_edge_B  : part.
integral : N_s_sli_C  : 1. : N_i_edge_C  : part.
integral : N_s_sli_N  : 1. : N_i_edge_N  : part.
integral : N_s_sli_O  : 1. : N_i_edge_O  : part.
integral : N_s_sli_Ne : 1. : N_i_edge_Ne : part.
integral : N_s_sli_Ar : 1. : N_i_edge_Ar : part.
integral : N_s_sli_W  : 1. : N_i_edge_W  : part.

integral : N_e_reg_01 : 1. : N_e_01  : part.
integral : N_e_reg_02 : 1. : N_e_02  : part.
integral : N_e_reg_03 : 1. : N_e_03  : part.
integral : N_e_reg_04 : 1. : N_e_04  : part.
integral : N_e_reg_05 : 1. : N_e_05  : part.
integral : N_e_reg_06 : 1. : N_e_06  : part.
integral : N_e_reg_07 : 1. : N_e_07  : part.
integral : N_e_reg_08 : 1. : N_e_08  : part.

integral : N_i_reg_01_H  : 1. : N_i_01_H   : part.
integral : N_i_reg_02_H  : 1. : N_i_02_H   : part.
integral : N_i_reg_03_H  : 1. : N_i_03_H   : part.
integral : N_i_reg_04_H  : 1. : N_i_04_H   : part.
integral : N_i_reg_05_H  : 1. : N_i_05_H   : part.
integral : N_i_reg_06_H  : 1. : N_i_06_H   : part.
integral : N_i_reg_07_H  : 1. : N_i_07_H   : part.
integral : N_i_reg_08_H  : 1. : N_i_08_H   : part.
integral : N_i_reg_01_D  : 1. : N_i_01_D   : part.
integral : N_i_reg_02_D  : 1. : N_i_02_D   : part.
integral : N_i_reg_03_D  : 1. : N_i_03_D   : part.
integral : N_i_reg_04_D  : 1. : N_i_04_D   : part.
integral : N_i_reg_05_D  : 1. : N_i_05_D   : part.
integral : N_i_reg_06_D  : 1. : N_i_06_D   : part.
integral : N_i_reg_07_D  : 1. : N_i_07_D   : part.
integral : N_i_reg_08_D  : 1. : N_i_08_D   : part.
integral : N_i_reg_01_T  : 1. : N_i_01_T   : part.
integral : N_i_reg_02_T  : 1. : N_i_02_T   : part.
integral : N_i_reg_03_T  : 1. : N_i_03_T   : part.
integral : N_i_reg_04_T  : 1. : N_i_04_T   : part.
integral : N_i_reg_05_T  : 1. : N_i_05_T   : part.
integral : N_i_reg_06_T  : 1. : N_i_06_T   : part.
integral : N_i_reg_07_T  : 1. : N_i_07_T   : part.
integral : N_i_reg_08_T  : 1. : N_i_08_T   : part.
integral : N_i_reg_01_He : 1. : N_i_01_He  : part.
integral : N_i_reg_02_He : 1. : N_i_02_He  : part.
integral : N_i_reg_03_He : 1. : N_i_03_He  : part.
integral : N_i_reg_04_He : 1. : N_i_04_He  : part.
integral : N_i_reg_06_He : 1. : N_i_05_He  : part.
integral : N_i_reg_07_He : 1. : N_i_06_He  : part.
integral : N_i_reg_08_He : 1. : N_i_07_He  : part.
integral : N_i_reg_09_He : 1. : N_i_08_He  : part.
integral : N_i_reg_01_Li : 1. : N_i_01_Li  : part.
integral : N_i_reg_02_Li : 1. : N_i_02_Li  : part.
integral : N_i_reg_03_Li : 1. : N_i_03_Li  : part.
integral : N_i_reg_04_Li : 1. : N_i_04_Li  : part.
integral : N_i_reg_05_Li : 1. : N_i_05_Li  : part.
integral : N_i_reg_06_Li : 1. : N_i_06_Li  : part.
integral : N_i_reg_07_Li : 1. : N_i_07_Li  : part.
integral : N_i_reg_08_Li : 1. : N_i_08_Li  : part.
integral : N_i_reg_01_Be : 1. : N_i_01_Be  : part.
integral : N_i_reg_02_Be : 1. : N_i_02_Be  : part.
integral : N_i_reg_03_Be : 1. : N_i_03_Be  : part.
integral : N_i_reg_04_Be : 1. : N_i_04_Be  : part.
integral : N_i_reg_05_Be : 1. : N_i_05_Be  : part.
integral : N_i_reg_06_Be : 1. : N_i_06_Be  : part.
integral : N_i_reg_07_Be : 1. : N_i_07_Be  : part.
integral : N_i_reg_08_Be : 1. : N_i_08_Be  : part.
integral : N_i_reg_01_B  : 1. : N_i_01_B   : part.
integral : N_i_reg_02_B  : 1. : N_i_02_B   : part.
integral : N_i_reg_03_B  : 1. : N_i_03_B   : part.
integral : N_i_reg_04_B  : 1. : N_i_04_B   : part.
integral : N_i_reg_05_B  : 1. : N_i_05_B   : part.
integral : N_i_reg_06_B  : 1. : N_i_06_B   : part.
integral : N_i_reg_07_B  : 1. : N_i_07_B   : part.
integral : N_i_reg_08_B  : 1. : N_i_08_B   : part.
integral : N_i_reg_01_C  : 1. : N_i_01_C   : part.
integral : N_i_reg_02_C  : 1. : N_i_02_C   : part.
integral : N_i_reg_03_C  : 1. : N_i_03_C   : part.
integral : N_i_reg_04_C  : 1. : N_i_04_C   : part.
integral : N_i_reg_05_C  : 1. : N_i_05_C   : part.
integral : N_i_reg_06_C  : 1. : N_i_06_C   : part.
integral : N_i_reg_07_C  : 1. : N_i_07_C   : part.
integral : N_i_reg_08_C  : 1. : N_i_08_C   : part.
integral : N_i_reg_01_N  : 1. : N_i_01_N   : part.
integral : N_i_reg_02_N  : 1. : N_i_02_N   : part.
integral : N_i_reg_03_N  : 1. : N_i_03_N   : part.
integral : N_i_reg_04_N  : 1. : N_i_04_N   : part.
integral : N_i_reg_05_N  : 1. : N_i_05_N   : part.
integral : N_i_reg_06_N  : 1. : N_i_06_N   : part.
integral : N_i_reg_07_N  : 1. : N_i_07_N   : part.
integral : N_i_reg_08_N  : 1. : N_i_08_N   : part.
integral : N_i_reg_01_O  : 1. : N_i_01_O   : part.
integral : N_i_reg_02_O  : 1. : N_i_02_O   : part.
integral : N_i_reg_03_O  : 1. : N_i_03_O   : part.
integral : N_i_reg_04_O  : 1. : N_i_04_O   : part.
integral : N_i_reg_05_O  : 1. : N_i_05_O   : part.
integral : N_i_reg_06_O  : 1. : N_i_06_O   : part.
integral : N_i_reg_07_O  : 1. : N_i_07_O   : part.
integral : N_i_reg_08_O  : 1. : N_i_08_O   : part.
integral : N_i_reg_01_Ne : 1. : N_i_01_Ne  : part.
integral : N_i_reg_02_Ne : 1. : N_i_02_Ne  : part.
integral : N_i_reg_03_Ne : 1. : N_i_03_Ne  : part.
integral : N_i_reg_04_Ne : 1. : N_i_04_Ne  : part.
integral : N_i_reg_05_Ne : 1. : N_i_05_Ne  : part.
integral : N_i_reg_06_Ne : 1. : N_i_06_Ne  : part.
integral : N_i_reg_07_Ne : 1. : N_i_07_Ne  : part.
integral : N_i_reg_08_Ne : 1. : N_i_08_Ne  : part.
integral : N_i_reg_01_Ar : 1. : N_i_01_Ar  : part.
integral : N_i_reg_02_Ar : 1. : N_i_02_Ar  : part.
integral : N_i_reg_03_Ar : 1. : N_i_03_Ar  : part.
integral : N_i_reg_04_Ar : 1. : N_i_04_Ar  : part.
integral : N_i_reg_05_Ar : 1. : N_i_05_Ar  : part.
integral : N_i_reg_06_Ar : 1. : N_i_06_Ar  : part.
integral : N_i_reg_07_Ar : 1. : N_i_07_Ar  : part.
integral : N_i_reg_08_Ar : 1. : N_i_08_Ar  : part.
integral : N_i_reg_01_Fe : 1. : N_i_01_Fe  : part.
integral : N_i_reg_02_Fe : 1. : N_i_02_Fe  : part.
integral : N_i_reg_03_Fe : 1. : N_i_03_Fe  : part.
integral : N_i_reg_04_Fe : 1. : N_i_04_Fe  : part.
integral : N_i_reg_05_Fe : 1. : N_i_05_Fe  : part.
integral : N_i_reg_06_Fe : 1. : N_i_06_Fe  : part.
integral : N_i_reg_07_Fe : 1. : N_i_07_Fe  : part.
integral : N_i_reg_08_Fe : 1. : N_i_08_Fe  : part.
integral : N_i_reg_01_W  : 1. : N_i_01_W   : part.
integral : N_i_reg_02_W  : 1. : N_i_02_W   : part.
integral : N_i_reg_03_W  : 1. : N_i_03_W   : part.
integral : N_i_reg_04_W  : 1. : N_i_04_W   : part.
integral : N_i_reg_05_W  : 1. : N_i_05_W   : part.
integral : N_i_reg_06_W  : 1. : N_i_06_W   : part.
integral : N_i_reg_07_W  : 1. : N_i_07_W   : part.
integral : N_i_reg_08_W  : 1. : N_i_08_W   : part.

integral : N_a_reg_01_H  : 1. : N_a_01_H   : part.
integral : N_a_reg_02_H  : 1. : N_a_02_H   : part.
integral : N_a_reg_03_H  : 1. : N_a_03_H   : part.
integral : N_a_reg_04_H  : 1. : N_a_04_H   : part.
integral : N_a_reg_05_H  : 1. : N_a_05_H   : part.
integral : N_a_reg_06_H  : 1. : N_a_06_H   : part.
integral : N_a_reg_07_H  : 1. : N_a_07_H   : part.
integral : N_a_reg_08_H  : 1. : N_a_08_H   : part.
integral : N_a_reg_01_D  : 1. : N_a_01_D   : part.
integral : N_a_reg_02_D  : 1. : N_a_02_D   : part.
integral : N_a_reg_03_D  : 1. : N_a_03_D   : part.
integral : N_a_reg_04_D  : 1. : N_a_04_D   : part.
integral : N_a_reg_05_D  : 1. : N_a_05_D   : part.
integral : N_a_reg_06_D  : 1. : N_a_06_D   : part.
integral : N_a_reg_07_D  : 1. : N_a_07_D   : part.
integral : N_a_reg_08_D  : 1. : N_a_08_D   : part.
integral : N_a_reg_01_T  : 1. : N_a_01_T   : part.
integral : N_a_reg_02_T  : 1. : N_a_02_T   : part.
integral : N_a_reg_03_T  : 1. : N_a_03_T   : part.
integral : N_a_reg_04_T  : 1. : N_a_04_T   : part.
integral : N_a_reg_05_T  : 1. : N_a_05_T   : part.
integral : N_a_reg_06_T  : 1. : N_a_06_T   : part.
integral : N_a_reg_07_T  : 1. : N_a_07_T   : part.
integral : N_a_reg_08_T  : 1. : N_a_08_T   : part.
integral : N_a_reg_01_He : 1. : N_a_01_He  : part.
integral : N_a_reg_02_He : 1. : N_a_02_He  : part.
integral : N_a_reg_03_He : 1. : N_a_03_He  : part.
integral : N_a_reg_04_He : 1. : N_a_04_He  : part.
integral : N_a_reg_05_He : 1. : N_a_05_He  : part.
integral : N_a_reg_06_He : 1. : N_a_06_He  : part.
integral : N_a_reg_07_He : 1. : N_a_07_He  : part.
integral : N_a_reg_08_He : 1. : N_a_08_He  : part.
integral : N_a_reg_01_Li : 1. : N_a_01_Li  : part.
integral : N_a_reg_02_Li : 1. : N_a_02_Li  : part.
integral : N_a_reg_03_Li : 1. : N_a_03_Li  : part.
integral : N_a_reg_04_Li : 1. : N_a_04_Li  : part.
integral : N_a_reg_05_Li : 1. : N_a_05_Li  : part.
integral : N_a_reg_06_Li : 1. : N_a_06_Li  : part.
integral : N_a_reg_07_Li : 1. : N_a_07_Li  : part.
integral : N_a_reg_08_Li : 1. : N_a_08_Li  : part.
integral : N_a_reg_01_Be : 1. : N_a_01_Be  : part.
integral : N_a_reg_02_Be : 1. : N_a_02_Be  : part.
integral : N_a_reg_03_Be : 1. : N_a_03_Be  : part.
integral : N_a_reg_04_Be : 1. : N_a_04_Be  : part.
integral : N_a_reg_05_Be : 1. : N_a_05_Be  : part.
integral : N_a_reg_06_Be : 1. : N_a_06_Be  : part.
integral : N_a_reg_07_Be : 1. : N_a_07_Be  : part.
integral : N_a_reg_08_Be : 1. : N_a_08_Be  : part.
integral : N_a_reg_01_B  : 1. : N_a_01_B   : part.
integral : N_a_reg_02_B  : 1. : N_a_02_B   : part.
integral : N_a_reg_03_B  : 1. : N_a_03_B   : part.
integral : N_a_reg_04_B  : 1. : N_a_04_B   : part.
integral : N_a_reg_05_B  : 1. : N_a_05_B   : part.
integral : N_a_reg_06_B  : 1. : N_a_06_B   : part.
integral : N_a_reg_07_B  : 1. : N_a_07_B   : part.
integral : N_a_reg_08_B  : 1. : N_a_08_B   : part.
integral : N_a_reg_01_C  : 1. : N_a_01_C   : part.
integral : N_a_reg_02_C  : 1. : N_a_02_C   : part.
integral : N_a_reg_03_C  : 1. : N_a_03_C   : part.
integral : N_a_reg_04_C  : 1. : N_a_04_C   : part.
integral : N_a_reg_05_C  : 1. : N_a_05_C   : part.
integral : N_a_reg_06_C  : 1. : N_a_06_C   : part.
integral : N_a_reg_07_C  : 1. : N_a_07_C   : part.
integral : N_a_reg_08_C  : 1. : N_a_08_C   : part.
integral : N_a_reg_01_N  : 1. : N_a_01_N   : part.
integral : N_a_reg_02_N  : 1. : N_a_02_N   : part.
integral : N_a_reg_03_N  : 1. : N_a_03_N   : part.
integral : N_a_reg_04_N  : 1. : N_a_04_N   : part.
integral : N_a_reg_05_N  : 1. : N_a_05_N   : part.
integral : N_a_reg_06_N  : 1. : N_a_06_N   : part.
integral : N_a_reg_07_N  : 1. : N_a_07_N   : part.
integral : N_a_reg_08_N  : 1. : N_a_08_N   : part.
integral : N_a_reg_01_O  : 1. : N_a_01_O   : part.
integral : N_a_reg_02_O  : 1. : N_a_02_O   : part.
integral : N_a_reg_03_O  : 1. : N_a_03_O   : part.
integral : N_a_reg_04_O  : 1. : N_a_04_O   : part.
integral : N_a_reg_05_O  : 1. : N_a_05_O   : part.
integral : N_a_reg_06_O  : 1. : N_a_06_O   : part.
integral : N_a_reg_07_O  : 1. : N_a_07_O   : part.
integral : N_a_reg_08_O  : 1. : N_a_08_O   : part.
integral : N_a_reg_01_Ne : 1. : N_a_01_Ne  : part.
integral : N_a_reg_02_Ne : 1. : N_a_02_Ne  : part.
integral : N_a_reg_03_Ne : 1. : N_a_03_Ne  : part.
integral : N_a_reg_04_Ne : 1. : N_a_04_Ne  : part.
integral : N_a_reg_05_Ne : 1. : N_a_05_Ne  : part.
integral : N_a_reg_06_Ne : 1. : N_a_06_Ne  : part.
integral : N_a_reg_07_Ne : 1. : N_a_07_Ne  : part.
integral : N_a_reg_08_Ne : 1. : N_a_08_Ne  : part.
integral : N_a_reg_01_Ar : 1. : N_a_01_Ar  : part.
integral : N_a_reg_02_Ar : 1. : N_a_02_Ar  : part.
integral : N_a_reg_03_Ar : 1. : N_a_03_Ar  : part.
integral : N_a_reg_04_Ar : 1. : N_a_04_Ar  : part.
integral : N_a_reg_05_Ar : 1. : N_a_05_Ar  : part.
integral : N_a_reg_06_Ar : 1. : N_a_06_Ar  : part.
integral : N_a_reg_07_Ar : 1. : N_a_07_Ar  : part.
integral : N_a_reg_08_Ar : 1. : N_a_08_Ar  : part.
integral : N_a_reg_01_Fe : 1. : N_a_01_Fe  : part.
integral : N_a_reg_02_Fe : 1. : N_a_02_Fe  : part.
integral : N_a_reg_03_Fe : 1. : N_a_03_Fe  : part.
integral : N_a_reg_04_Fe : 1. : N_a_04_Fe  : part.
integral : N_a_reg_05_Fe : 1. : N_a_05_Fe  : part.
integral : N_a_reg_06_Fe : 1. : N_a_06_Fe  : part.
integral : N_a_reg_07_Fe : 1. : N_a_07_Fe  : part.
integral : N_a_reg_08_Fe : 1. : N_a_08_Fe  : part.
integral : N_a_reg_01_W  : 1. : N_a_01_W   : part.
integral : N_a_reg_02_W  : 1. : N_a_02_W   : part.
integral : N_a_reg_03_W  : 1. : N_a_03_W   : part.
integral : N_a_reg_04_W  : 1. : N_a_04_W   : part.
integral : N_a_reg_05_W  : 1. : N_a_05_W   : part.
integral : N_a_reg_06_W  : 1. : N_a_06_W   : part.
integral : N_a_reg_07_W  : 1. : N_a_07_W   : part.
integral : N_a_reg_08_W  : 1. : N_a_08_W   : part.

integral : imp_rad_01 : -1.e-6 : Q_imp_rad_01 : MW
integral : imp_rad_02 : -1.e-6 : Q_imp_rad_02 : MW
integral : imp_rad_03 : -1.e-6 : Q_imp_rad_03 : MW
integral : imp_rad_04 : -1.e-6 : Q_imp_rad_04 : MW
integral : imp_rad_05 : -1.e-6 : Q_imp_rad_05 : MW
integral : imp_rad_06 : -1.e-6 : Q_imp_rad_06 : MW
integral : imp_rad_07 : -1.e-6 : Q_imp_rad_07 : MW
integral : imp_rad_08 : -1.e-6 : Q_imp_rad_08 : MW
integral : neu_rad_01 : -1.e-6 : Q_neut_rad_01 : MW
integral : neu_rad_02 : -1.e-6 : Q_neut_rad_02 : MW
integral : neu_rad_03 : -1.e-6 : Q_neut_rad_03 : MW
integral : neu_rad_04 : -1.e-6 : Q_neut_rad_04 : MW
integral : neu_rad_05 : -1.e-6 : Q_neut_rad_05 : MW
integral : neu_rad_06 : -1.e-6 : Q_neut_rad_06 : MW
integral : neu_rad_07 : -1.e-6 : Q_neut_rad_07 : MW
integral : neu_rad_08 : -1.e-6 : Q_neut_rad_08 : MW
integral : tot_rad_01 : -1.e-6 : Q_tot_rad_01 : MW
integral : tot_rad_02 : -1.e-6 : Q_tot_rad_02 : MW
integral : tot_rad_03 : -1.e-6 : Q_tot_rad_03 : MW
integral : tot_rad_04 : -1.e-6 : Q_tot_rad_04 : MW
integral : tot_rad_05 : -1.e-6 : Q_tot_rad_05 : MW
integral : tot_rad_06 : -1.e-6 : Q_tot_rad_06 : MW
integral : tot_rad_07 : -1.e-6 : Q_tot_rad_07 : MW
integral : tot_rad_08 : -1.e-6 : Q_tot_rad_08 : MW
